// Code generated by Fern. DO NOT EDIT.

package client

import (
	actions "github.com/mavenagi/mavenagi-go/actions"
	agents "github.com/mavenagi/mavenagi-go/agents"
	analytics "github.com/mavenagi/mavenagi-go/analytics"
	appsettings "github.com/mavenagi/mavenagi-go/appsettings"
	assets "github.com/mavenagi/mavenagi-go/assets"
	conversation "github.com/mavenagi/mavenagi-go/conversation"
	core "github.com/mavenagi/mavenagi-go/core"
	events "github.com/mavenagi/mavenagi-go/events"
	inbox "github.com/mavenagi/mavenagi-go/inbox"
	internal "github.com/mavenagi/mavenagi-go/internal"
	knowledge "github.com/mavenagi/mavenagi-go/knowledge"
	option "github.com/mavenagi/mavenagi-go/option"
	organizations "github.com/mavenagi/mavenagi-go/organizations"
	segments "github.com/mavenagi/mavenagi-go/segments"
	translations "github.com/mavenagi/mavenagi-go/translations"
	triggers "github.com/mavenagi/mavenagi-go/triggers"
	users "github.com/mavenagi/mavenagi-go/users"
	os "os"
)

type MavenAGI struct {
	Actions       *actions.Client
	Agents        *agents.Client
	Analytics     *analytics.Client
	AppSettings   *appsettings.Client
	Assets        *assets.Client
	Conversation  *conversation.Client
	Events        *events.Client
	Inbox         *inbox.Client
	Knowledge     *knowledge.Client
	Organizations *organizations.Client
	Segments      *segments.Client
	Translations  *translations.Client
	Triggers      *triggers.Client
	Users         *users.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewMavenAGI(opts ...option.RequestOption) *MavenAGI {
	options := core.NewRequestOptions(opts...)
	if options.AppId == "" {
		options.AppId = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &MavenAGI{
		Actions:       actions.NewClient(options),
		Agents:        agents.NewClient(options),
		Analytics:     analytics.NewClient(options),
		AppSettings:   appsettings.NewClient(options),
		Assets:        assets.NewClient(options),
		Conversation:  conversation.NewClient(options),
		Events:        events.NewClient(options),
		Inbox:         inbox.NewClient(options),
		Knowledge:     knowledge.NewClient(options),
		Organizations: organizations.NewClient(options),
		Segments:      segments.NewClient(options),
		Translations:  translations.NewClient(options),
		Triggers:      triggers.NewClient(options),
		Users:         users.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
