// Code generated by Fern. DO NOT EDIT.

package appdirectory

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Lists apps available to install on the agent, with filtering and pagination.
func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.DirectoryAppsSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.AppsResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Gets an app and its installation status for the agent.
func (c *Client) Get(
	ctx context.Context,
	appID string,
	opts ...option.RequestOption,
) (*mavenagigo.MarketplaceAppDetail, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		appID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Installs the app on the agent, or updates settings for an existing installation. Re-runs the postInstall lifecycle hook on each call.
func (c *Client) Install(
	ctx context.Context,
	appID string,
	request *mavenagigo.InstallDirectoryAppRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Install(
		ctx,
		appID,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Uninstalls the app from the agent.
func (c *Client) Uninstall(
	ctx context.Context,
	appID string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Uninstall(
		ctx,
		appID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Gets a url for downloading a file app setting.
func (c *Client) GetSettingDownloadURL(
	ctx context.Context,
	appID string,
	settingsKey string,
	opts ...option.RequestOption,
) (*mavenagigo.GetDirectoryAppSettingDownloadURLResponse, error) {
	response, err := c.WithRawResponse.GetSettingDownloadURL(
		ctx,
		appID,
		settingsKey,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Gets a presigned url for uploading a file app setting before installation.
func (c *Client) GetSettingUploadURL(
	ctx context.Context,
	appID string,
	settingsKey string,
	request *mavenagigo.GetAppSettingUploadURLRequest,
	opts ...option.RequestOption,
) (*mavenagigo.GetDirectoryAppSettingUploadURLResponse, error) {
	response, err := c.WithRawResponse.GetSettingUploadURL(
		ctx,
		appID,
		settingsKey,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
