// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
	time "time"
)

var (
	deleteCapabilityByTypeRequestFieldAppID              = big.NewInt(1 << 0)
	deleteCapabilityByTypeRequestFieldVariantReferenceID = big.NewInt(1 << 1)
	deleteCapabilityByTypeRequestFieldVariantAppID       = big.NewInt(1 << 2)
)

type DeleteCapabilityByTypeRequest struct {
	// The app that owns the capability. Defaults to the calling app.
	AppID *string `json:"-" url:"appId,omitempty"`
	// The agent variant to stage an intelligent field's delete in, by reference ID.
	// Required for an intelligent field on an agent with versioned intelligent fields; a
	// request that omits it there is rejected with reason `VARIANT_REQUIRED`.
	// The other capability types aren't versioned and are the same in every variant,
	// though a named variant must still exist.
	VariantReferenceID *string `json:"-" url:"variantReferenceId,omitempty"`
	// The app that owns the agent variant. Defaults to the calling app.
	VariantAppID *string `json:"-" url:"variantAppId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteCapabilityByTypeRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteCapabilityByTypeRequest) SetAppID(appID *string) {
	d.AppID = appID
	d.require(deleteCapabilityByTypeRequestFieldAppID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteCapabilityByTypeRequest) SetVariantReferenceID(variantReferenceID *string) {
	d.VariantReferenceID = variantReferenceID
	d.require(deleteCapabilityByTypeRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteCapabilityByTypeRequest) SetVariantAppID(variantAppID *string) {
	d.VariantAppID = variantAppID
	d.require(deleteCapabilityByTypeRequestFieldVariantAppID)
}

var (
	getCapabilityByTypeRequestFieldAppID              = big.NewInt(1 << 0)
	getCapabilityByTypeRequestFieldVariantReferenceID = big.NewInt(1 << 1)
	getCapabilityByTypeRequestFieldVariantAppID       = big.NewInt(1 << 2)
)

type GetCapabilityByTypeRequest struct {
	// The app that owns the capability. Defaults to the calling app, which is what an app
	// managing its own capabilities wants.
	AppID *string `json:"-" url:"appId,omitempty"`
	// The agent variant to read an intelligent field through, by reference ID.
	// Required for an intelligent field on an agent with versioned intelligent fields; a
	// request that omits it there is rejected with reason `VARIANT_REQUIRED`. Otherwise,
	// if omitted, the agent's only variant is used.
	// The other capability types aren't versioned and are the same in every variant,
	// though a named variant must still exist.
	VariantReferenceID *string `json:"-" url:"variantReferenceId,omitempty"`
	// The app that owns the agent variant. Defaults to the calling app.
	VariantAppID *string `json:"-" url:"variantAppId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCapabilityByTypeRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCapabilityByTypeRequest) SetAppID(appID *string) {
	g.AppID = appID
	g.require(getCapabilityByTypeRequestFieldAppID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCapabilityByTypeRequest) SetVariantReferenceID(variantReferenceID *string) {
	g.VariantReferenceID = variantReferenceID
	g.require(getCapabilityByTypeRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCapabilityByTypeRequest) SetVariantAppID(variantAppID *string) {
	g.VariantAppID = variantAppID
	g.require(getCapabilityByTypeRequestFieldVariantAppID)
}

var (
	patchCapabilityByTypeRequestFieldAppID              = big.NewInt(1 << 0)
	patchCapabilityByTypeRequestFieldVariantReferenceID = big.NewInt(1 << 1)
	patchCapabilityByTypeRequestFieldVariantAppID       = big.NewInt(1 << 2)
	patchCapabilityByTypeRequestFieldStatus             = big.NewInt(1 << 3)
)

type PatchCapabilityByTypeRequest struct {
	// The app that owns the capability. Defaults to the calling app.
	AppID *string `json:"-" url:"appId,omitempty"`
	// The agent variant to stage an intelligent field's status change in, by reference ID.
	// Required for an intelligent field on an agent with versioned intelligent fields; a
	// request that omits it there is rejected with reason `VARIANT_REQUIRED`.
	// The other capability types aren't versioned and are the same in every variant,
	// though a named variant must still exist.
	VariantReferenceID *string `json:"-" url:"variantReferenceId,omitempty"`
	// The app that owns the agent variant. Defaults to the calling app.
	VariantAppID *string `json:"-" url:"variantAppId,omitempty"`
	// Whether the agent uses this capability. Use ACTIVE to start and INACTIVE to stop;
	// deleting is done through the delete endpoint, so DELETED is rejected here.
	Status *CapabilityStatus `json:"status,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PatchCapabilityByTypeRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchCapabilityByTypeRequest) SetAppID(appID *string) {
	p.AppID = appID
	p.require(patchCapabilityByTypeRequestFieldAppID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchCapabilityByTypeRequest) SetVariantReferenceID(variantReferenceID *string) {
	p.VariantReferenceID = variantReferenceID
	p.require(patchCapabilityByTypeRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchCapabilityByTypeRequest) SetVariantAppID(variantAppID *string) {
	p.VariantAppID = variantAppID
	p.require(patchCapabilityByTypeRequestFieldVariantAppID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchCapabilityByTypeRequest) SetStatus(status *CapabilityStatus) {
	p.Status = status
	p.require(patchCapabilityByTypeRequestFieldStatus)
}

var (
	capabilitiesSearchRequestFieldCapabilityTypes         = big.NewInt(1 << 0)
	capabilitiesSearchRequestFieldStatuses                = big.NewInt(1 << 1)
	capabilitiesSearchRequestFieldAppIDs                  = big.NewInt(1 << 2)
	capabilitiesSearchRequestFieldName                    = big.NewInt(1 << 3)
	capabilitiesSearchRequestFieldDescription             = big.NewInt(1 << 4)
	capabilitiesSearchRequestFieldUserInteractionRequired = big.NewInt(1 << 5)
	capabilitiesSearchRequestFieldSortID                  = big.NewInt(1 << 6)
	capabilitiesSearchRequestFieldVariantReferenceID      = big.NewInt(1 << 7)
	capabilitiesSearchRequestFieldVariantAppID            = big.NewInt(1 << 8)
)

type CapabilitiesSearchRequest struct {
	// Page number to return, defaults to 0
	Page *int `json:"page,omitempty" url:"-"`
	// The size of the page to return, defaults to 20. Max 1000.
	Size *int `json:"size,omitempty" url:"-"`
	// Whether to sort descending, defaults to true
	SortDesc *bool `json:"sortDesc,omitempty" url:"-"`
	// Only return capabilities of these kinds. Omit for every kind.
	CapabilityTypes []CapabilityType `json:"capabilityTypes,omitempty" url:"-"`
	// Only return capabilities the agent does or does not use. Deleted capabilities are
	// never searchable, so `DELETED` is rejected here rather than matching nothing.
	Statuses []CapabilityStatus `json:"statuses,omitempty" url:"-"`
	// Only return capabilities owned by these apps.
	AppIDs []string `json:"appIds,omitempty" url:"-"`
	// Only return capabilities whose name matches this text.
	Name *string `json:"name,omitempty" url:"-"`
	// Only return capabilities whose description matches this text.
	Description *string `json:"description,omitempty" url:"-"`
	// Only return capabilities that do or do not require user interaction. Only Actions
	// can require it, so filtering on true returns Actions alone.
	UserInteractionRequired *bool `json:"userInteractionRequired,omitempty" url:"-"`
	// The field to sort by. Defaults to when the capability was created.
	SortID *CapabilitySortField `json:"sortId,omitempty" url:"-"`
	// The agent variant to read intelligent field versions through. Required on an agent
	// with versioned intelligent fields unless `capabilityTypes` excludes them; a
	// request that omits it there is rejected with reason `VARIANT_REQUIRED`. Otherwise,
	// if omitted, the agent's only variant is used.
	VariantReferenceID *string `json:"variantReferenceId,omitempty" url:"-"`
	// The app that owns the agent variant. Defaults to the calling app.
	VariantAppID *string `json:"variantAppId,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CapabilitiesSearchRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCapabilityTypes sets the CapabilityTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetCapabilityTypes(capabilityTypes []CapabilityType) {
	c.CapabilityTypes = capabilityTypes
	c.require(capabilitiesSearchRequestFieldCapabilityTypes)
}

// SetStatuses sets the Statuses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetStatuses(statuses []CapabilityStatus) {
	c.Statuses = statuses
	c.require(capabilitiesSearchRequestFieldStatuses)
}

// SetAppIDs sets the AppIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetAppIDs(appIDs []string) {
	c.AppIDs = appIDs
	c.require(capabilitiesSearchRequestFieldAppIDs)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetName(name *string) {
	c.Name = name
	c.require(capabilitiesSearchRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetDescription(description *string) {
	c.Description = description
	c.require(capabilitiesSearchRequestFieldDescription)
}

// SetUserInteractionRequired sets the UserInteractionRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetUserInteractionRequired(userInteractionRequired *bool) {
	c.UserInteractionRequired = userInteractionRequired
	c.require(capabilitiesSearchRequestFieldUserInteractionRequired)
}

// SetSortID sets the SortID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetSortID(sortID *CapabilitySortField) {
	c.SortID = sortID
	c.require(capabilitiesSearchRequestFieldSortID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetVariantReferenceID(variantReferenceID *string) {
	c.VariantReferenceID = variantReferenceID
	c.require(capabilitiesSearchRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchRequest) SetVariantAppID(variantAppID *string) {
	c.VariantAppID = variantAppID
	c.require(capabilitiesSearchRequestFieldVariantAppID)
}

var (
	capabilitiesSearchResponseFieldNumber        = big.NewInt(1 << 0)
	capabilitiesSearchResponseFieldSize          = big.NewInt(1 << 1)
	capabilitiesSearchResponseFieldTotalElements = big.NewInt(1 << 2)
	capabilitiesSearchResponseFieldTotalPages    = big.NewInt(1 << 3)
	capabilitiesSearchResponseFieldCapabilities  = big.NewInt(1 << 4)
)

type CapabilitiesSearchResponse struct {
	// The page being returned, starts at 0
	Number int `json:"number" url:"number"`
	// The number of elements in this page
	Size int `json:"size" url:"size"`
	// The total number of elements in the collection
	TotalElements int64 `json:"totalElements" url:"totalElements"`
	// The total number of pages in the collection
	TotalPages int `json:"totalPages" url:"totalPages"`
	// The capabilities on this page, in the order the request asked for.
	Capabilities []*CapabilitySummary `json:"capabilities" url:"capabilities"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CapabilitiesSearchResponse) GetNumber() int {
	if c == nil {
		return 0
	}
	return c.Number
}

func (c *CapabilitiesSearchResponse) GetSize() int {
	if c == nil {
		return 0
	}
	return c.Size
}

func (c *CapabilitiesSearchResponse) GetTotalElements() int64 {
	if c == nil {
		return 0
	}
	return c.TotalElements
}

func (c *CapabilitiesSearchResponse) GetTotalPages() int {
	if c == nil {
		return 0
	}
	return c.TotalPages
}

func (c *CapabilitiesSearchResponse) GetCapabilities() []*CapabilitySummary {
	if c == nil {
		return nil
	}
	return c.Capabilities
}

func (c *CapabilitiesSearchResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CapabilitiesSearchResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchResponse) SetNumber(number int) {
	c.Number = number
	c.require(capabilitiesSearchResponseFieldNumber)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchResponse) SetSize(size int) {
	c.Size = size
	c.require(capabilitiesSearchResponseFieldSize)
}

// SetTotalElements sets the TotalElements field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchResponse) SetTotalElements(totalElements int64) {
	c.TotalElements = totalElements
	c.require(capabilitiesSearchResponseFieldTotalElements)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchResponse) SetTotalPages(totalPages int) {
	c.TotalPages = totalPages
	c.require(capabilitiesSearchResponseFieldTotalPages)
}

// SetCapabilities sets the Capabilities field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitiesSearchResponse) SetCapabilities(capabilities []*CapabilitySummary) {
	c.Capabilities = capabilities
	c.require(capabilitiesSearchResponseFieldCapabilities)
}

func (c *CapabilitiesSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CapabilitiesSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CapabilitiesSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CapabilitiesSearchResponse) MarshalJSON() ([]byte, error) {
	type embed CapabilitiesSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CapabilitiesSearchResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// One of an agent's capabilities, of whichever kind. Each variant is the very type that
// capability's own API returns, so nothing is redefined here.
//
// The discriminant is `capabilityType` rather than `type` because an event trigger already has
// a `type` of its own. Naming it apart is what lets each variant keep its own fields unchanged.
type CapabilityResponse struct {
	CapabilityType      string
	Action              *ActionResponse
	Trigger             *EventTriggerResponse
	IntelligentField    *IntelligentFieldResponse
	ConversationKickoff *ConversationKickoff
}

func (c *CapabilityResponse) GetCapabilityType() string {
	if c == nil {
		return ""
	}
	return c.CapabilityType
}

func (c *CapabilityResponse) GetAction() *ActionResponse {
	if c == nil {
		return nil
	}
	return c.Action
}

func (c *CapabilityResponse) GetTrigger() *EventTriggerResponse {
	if c == nil {
		return nil
	}
	return c.Trigger
}

func (c *CapabilityResponse) GetIntelligentField() *IntelligentFieldResponse {
	if c == nil {
		return nil
	}
	return c.IntelligentField
}

func (c *CapabilityResponse) GetConversationKickoff() *ConversationKickoff {
	if c == nil {
		return nil
	}
	return c.ConversationKickoff
}

func (c *CapabilityResponse) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		CapabilityType string `json:"capabilityType"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.CapabilityType = unmarshaler.CapabilityType
	if unmarshaler.CapabilityType == "" {
		return fmt.Errorf("%T did not include discriminant capabilityType", c)
	}
	switch unmarshaler.CapabilityType {
	case "ACTION":
		value := new(ActionResponse)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Action = value
	case "TRIGGER":
		value := new(EventTriggerResponse)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Trigger = value
	case "INTELLIGENT_FIELD":
		value := new(IntelligentFieldResponse)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.IntelligentField = value
	case "CONVERSATION_KICKOFF":
		value := new(ConversationKickoff)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.ConversationKickoff = value
	}
	return nil
}

func (c CapabilityResponse) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.Action != nil {
		return internal.MarshalJSONWithExtraProperty(c.Action, "capabilityType", "ACTION")
	}
	if c.Trigger != nil {
		return internal.MarshalJSONWithExtraProperty(c.Trigger, "capabilityType", "TRIGGER")
	}
	if c.IntelligentField != nil {
		return internal.MarshalJSONWithExtraProperty(c.IntelligentField, "capabilityType", "INTELLIGENT_FIELD")
	}
	if c.ConversationKickoff != nil {
		return internal.MarshalJSONWithExtraProperty(c.ConversationKickoff, "capabilityType", "CONVERSATION_KICKOFF")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CapabilityResponseVisitor interface {
	VisitAction(*ActionResponse) error
	VisitTrigger(*EventTriggerResponse) error
	VisitIntelligentField(*IntelligentFieldResponse) error
	VisitConversationKickoff(*ConversationKickoff) error
}

func (c *CapabilityResponse) Accept(visitor CapabilityResponseVisitor) error {
	if c.Action != nil {
		return visitor.VisitAction(c.Action)
	}
	if c.Trigger != nil {
		return visitor.VisitTrigger(c.Trigger)
	}
	if c.IntelligentField != nil {
		return visitor.VisitIntelligentField(c.IntelligentField)
	}
	if c.ConversationKickoff != nil {
		return visitor.VisitConversationKickoff(c.ConversationKickoff)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *CapabilityResponse) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.Action != nil {
		fields = append(fields, "ACTION")
	}
	if c.Trigger != nil {
		fields = append(fields, "TRIGGER")
	}
	if c.IntelligentField != nil {
		fields = append(fields, "INTELLIGENT_FIELD")
	}
	if c.ConversationKickoff != nil {
		fields = append(fields, "CONVERSATION_KICKOFF")
	}
	if len(fields) == 0 {
		if c.CapabilityType != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.CapabilityType)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.CapabilityType != "" {
		field := fields[0]
		if c.CapabilityType != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.CapabilityType,
				c,
			)
		}
	}
	return nil
}

// The fields a capability search can be ordered by.
type CapabilitySortField string

const (
	CapabilitySortFieldCreatedAt CapabilitySortField = "CreatedAt"
	CapabilitySortFieldName      CapabilitySortField = "Name"
	CapabilitySortFieldType      CapabilitySortField = "Type"
)

func NewCapabilitySortFieldFromString(s string) (CapabilitySortField, error) {
	switch s {
	case "CreatedAt":
		return CapabilitySortFieldCreatedAt, nil
	case "Name":
		return CapabilitySortFieldName, nil
	case "Type":
		return CapabilitySortFieldType, nil
	}
	var t CapabilitySortField
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CapabilitySortField) Ptr() *CapabilitySortField {
	return &c
}

// What every capability has in common, whatever kind it is, plus which kind it is and how to
// address it.
var (
	capabilitySummaryFieldName           = big.NewInt(1 << 0)
	capabilitySummaryFieldDescription    = big.NewInt(1 << 1)
	capabilitySummaryFieldCreatedAt      = big.NewInt(1 << 2)
	capabilitySummaryFieldUpdatedAt      = big.NewInt(1 << 3)
	capabilitySummaryFieldStatus         = big.NewInt(1 << 4)
	capabilitySummaryFieldCapabilityID   = big.NewInt(1 << 5)
	capabilitySummaryFieldCapabilityType = big.NewInt(1 << 6)
)

type CapabilitySummary struct {
	// The capability's display name, shown to whoever manages the agent. A trigger registered
	// without one is named after the app that registered it and the event it fires on.
	Name string `json:"name" url:"name"`
	// What the capability does. Shown to whoever manages the agent, and for the types the LLM
	// can choose between, used to decide when the capability applies.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// When the capability was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// When the capability was last modified.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// Whether the agent uses this capability, and whether it still exists.
	Status CapabilityStatus `json:"status" url:"status"`
	// ID that uniquely identifies this capability.
	CapabilityID *EntityID `json:"capabilityId" url:"capabilityId"`
	// Which kind of capability this is, and the path segment that addresses it.
	CapabilityType CapabilityType `json:"capabilityType" url:"capabilityType"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CapabilitySummary) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CapabilitySummary) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CapabilitySummary) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CapabilitySummary) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CapabilitySummary) GetStatus() CapabilityStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CapabilitySummary) GetCapabilityID() *EntityID {
	if c == nil {
		return nil
	}
	return c.CapabilityID
}

func (c *CapabilitySummary) GetCapabilityType() CapabilityType {
	if c == nil {
		return ""
	}
	return c.CapabilityType
}

func (c *CapabilitySummary) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CapabilitySummary) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetName(name string) {
	c.Name = name
	c.require(capabilitySummaryFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetDescription(description *string) {
	c.Description = description
	c.require(capabilitySummaryFieldDescription)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(capabilitySummaryFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(capabilitySummaryFieldUpdatedAt)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetStatus(status CapabilityStatus) {
	c.Status = status
	c.require(capabilitySummaryFieldStatus)
}

// SetCapabilityID sets the CapabilityID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetCapabilityID(capabilityID *EntityID) {
	c.CapabilityID = capabilityID
	c.require(capabilitySummaryFieldCapabilityID)
}

// SetCapabilityType sets the CapabilityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CapabilitySummary) SetCapabilityType(capabilityType CapabilityType) {
	c.CapabilityType = capabilityType
	c.require(capabilitySummaryFieldCapabilityType)
}

func (c *CapabilitySummary) UnmarshalJSON(data []byte) error {
	type embed CapabilitySummary
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CapabilitySummary(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CapabilitySummary) MarshalJSON() ([]byte, error) {
	type embed CapabilitySummary
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CapabilitySummary) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
