// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
	time "time"
)

// Controls whether this charter's direct children mutually exclude each other when more than
// one of them matches a turn. Set on the parent (group) charter; it has no effect on a charter
// with no children.
//
//   - DEFAULT: Standard behavior. A parent's children are mutually exclusive only when all of that
//     parent's children are leaves — when they compete, only the highest-priority child
//     (lowest userRank) is kept. If any child is itself a group (has children of its
//     own), none of the parent's children are excluded.
//   - ALLOW_OVERLAP: This charter's children never mutually exclude each other. Every child that
//     matches is kept.
type CharterChildrenExclusionPolicy string

const (
	CharterChildrenExclusionPolicyDefault      CharterChildrenExclusionPolicy = "DEFAULT"
	CharterChildrenExclusionPolicyAllowOverlap CharterChildrenExclusionPolicy = "ALLOW_OVERLAP"
)

func NewCharterChildrenExclusionPolicyFromString(s string) (CharterChildrenExclusionPolicy, error) {
	switch s {
	case "DEFAULT":
		return CharterChildrenExclusionPolicyDefault, nil
	case "ALLOW_OVERLAP":
		return CharterChildrenExclusionPolicyAllowOverlap, nil
	}
	var t CharterChildrenExclusionPolicy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CharterChildrenExclusionPolicy) Ptr() *CharterChildrenExclusionPolicy {
	return &c
}

// The lifecycle status of a charter.
//
//   - ACTIVE: The charter is active and will be evaluated during Q&A. The caller is responsible
//     for ensuring ancestor charters are also ACTIVE if the full subtree should be reachable.
//   - INACTIVE: The charter is inactive. It retains its rank among siblings and its descendants retain their statuses.
//     However, it and its descendants are skipped during runtime Q&A evaluation.
//   - DELETED: The charter has been soft deleted. Excluded from searches and cannot be modified.
//     Deleting a charter cascades to all descendants (they are also soft-deleted).
type CharterStatus string

const (
	CharterStatusActive   CharterStatus = "ACTIVE"
	CharterStatusInactive CharterStatus = "INACTIVE"
	CharterStatusDeleted  CharterStatus = "DELETED"
)

func NewCharterStatusFromString(s string) (CharterStatus, error) {
	switch s {
	case "ACTIVE":
		return CharterStatusActive, nil
	case "INACTIVE":
		return CharterStatusInactive, nil
	case "DELETED":
		return CharterStatusDeleted, nil
	}
	var t CharterStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CharterStatus) Ptr() *CharterStatus {
	return &c
}

// A lightweight charter representation for search results and ancestor paths.
// Use the get endpoint to retrieve the full charter with references, manual, and children.
var (
	charterSummaryFieldCharterID               = big.NewInt(1 << 0)
	charterSummaryFieldName                    = big.NewInt(1 << 1)
	charterSummaryFieldSegmentSummary          = big.NewInt(1 << 2)
	charterSummaryFieldPrecondition            = big.NewInt(1 << 3)
	charterSummaryFieldParentCharterID         = big.NewInt(1 << 4)
	charterSummaryFieldStatus                  = big.NewInt(1 << 5)
	charterSummaryFieldType                    = big.NewInt(1 << 6)
	charterSummaryFieldChildrenExclusionPolicy = big.NewInt(1 << 7)
	charterSummaryFieldCreatedAt               = big.NewInt(1 << 8)
	charterSummaryFieldUpdatedAt               = big.NewInt(1 << 9)
)

type CharterSummary struct {
	// ID that uniquely identifies this charter.
	CharterID *EntityID `json:"charterId" url:"charterId"`
	// The display name of the charter.
	Name string `json:"name" url:"name"`
	// The segment backing this charter's rule. An implementation detail of `precondition`;
	// read that instead.
	SegmentSummary *SegmentSummary `json:"segmentSummary,omitempty" url:"segmentSummary,omitempty"`
	// The rule controlling when this charter applies, read from the charter's backing
	// segment. Null means wildcard (always matches).
	Precondition *PreconditionResponse `json:"precondition,omitempty" url:"precondition,omitempty"`
	// The ID of the parent charter. Null for root-level charters.
	ParentCharterID *EntityID `json:"parentCharterId,omitempty" url:"parentCharterId,omitempty"`
	// The lifecycle status of this charter.
	Status CharterStatus `json:"status" url:"status"`
	// The behavioral mode for this charter. Defaults to STANDARD.
	Type *CharterType `json:"type,omitempty" url:"type,omitempty"`
	// Whether this charter's children mutually exclude each other. Defaults to DEFAULT.
	ChildrenExclusionPolicy *CharterChildrenExclusionPolicy `json:"childrenExclusionPolicy,omitempty" url:"childrenExclusionPolicy,omitempty"`
	// The date and time this charter was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// The date and time this charter was last updated.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CharterSummary) GetCharterID() *EntityID {
	if c == nil {
		return nil
	}
	return c.CharterID
}

func (c *CharterSummary) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CharterSummary) GetSegmentSummary() *SegmentSummary {
	if c == nil {
		return nil
	}
	return c.SegmentSummary
}

func (c *CharterSummary) GetPrecondition() *PreconditionResponse {
	if c == nil {
		return nil
	}
	return c.Precondition
}

func (c *CharterSummary) GetParentCharterID() *EntityID {
	if c == nil {
		return nil
	}
	return c.ParentCharterID
}

func (c *CharterSummary) GetStatus() CharterStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CharterSummary) GetType() *CharterType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CharterSummary) GetChildrenExclusionPolicy() *CharterChildrenExclusionPolicy {
	if c == nil {
		return nil
	}
	return c.ChildrenExclusionPolicy
}

func (c *CharterSummary) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CharterSummary) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CharterSummary) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CharterSummary) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCharterID sets the CharterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetCharterID(charterID *EntityID) {
	c.CharterID = charterID
	c.require(charterSummaryFieldCharterID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetName(name string) {
	c.Name = name
	c.require(charterSummaryFieldName)
}

// SetSegmentSummary sets the SegmentSummary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetSegmentSummary(segmentSummary *SegmentSummary) {
	c.SegmentSummary = segmentSummary
	c.require(charterSummaryFieldSegmentSummary)
}

// SetPrecondition sets the Precondition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetPrecondition(precondition *PreconditionResponse) {
	c.Precondition = precondition
	c.require(charterSummaryFieldPrecondition)
}

// SetParentCharterID sets the ParentCharterID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetParentCharterID(parentCharterID *EntityID) {
	c.ParentCharterID = parentCharterID
	c.require(charterSummaryFieldParentCharterID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetStatus(status CharterStatus) {
	c.Status = status
	c.require(charterSummaryFieldStatus)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetType(type_ *CharterType) {
	c.Type = type_
	c.require(charterSummaryFieldType)
}

// SetChildrenExclusionPolicy sets the ChildrenExclusionPolicy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetChildrenExclusionPolicy(childrenExclusionPolicy *CharterChildrenExclusionPolicy) {
	c.ChildrenExclusionPolicy = childrenExclusionPolicy
	c.require(charterSummaryFieldChildrenExclusionPolicy)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetCreatedAt(createdAt time.Time) {
	c.CreatedAt = createdAt
	c.require(charterSummaryFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CharterSummary) SetUpdatedAt(updatedAt time.Time) {
	c.UpdatedAt = updatedAt
	c.require(charterSummaryFieldUpdatedAt)
}

func (c *CharterSummary) UnmarshalJSON(data []byte) error {
	type embed CharterSummary
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CharterSummary(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CharterSummary) MarshalJSON() ([]byte, error) {
	type embed CharterSummary
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		UpdatedAt: internal.NewDateTime(c.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CharterSummary) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The behavioral mode for a charter.
//
//   - STANDARD: Default. The charter's manual is delivered to the LLM as instructions,
//     concatenated with ancestor charter manuals before delivery.
//
//   - STRICT_RETURN: When matched, this charter's manual becomes the response: it is returned
//     verbatim, without invoking the LLM. The charter cannot have children, and
//     its manual must be non-blank — the manual is the response.
//
//     A STRICT_RETURN charter references nothing: both `knowledgeBaseIds` and
//     `actionIds` must be empty, and a create or update supplying either is
//     rejected. With no LLM in the turn there is nothing to consult a knowledge
//     base or to choose an action.
//
//     A STRICT_RETURN charter is matched exactly like any other charter — same
//     ordering and mutual-exclusion rules. The only difference is what a match
//     does: the first matched STRICT_RETURN charter takes over the turn, so its
//     manual is the whole response and every other matched charter is ignored.
//     (At most one applies per turn.)
type CharterType string

const (
	CharterTypeStandard     CharterType = "STANDARD"
	CharterTypeStrictReturn CharterType = "STRICT_RETURN"
)

func NewCharterTypeFromString(s string) (CharterType, error) {
	switch s {
	case "STANDARD":
		return CharterTypeStandard, nil
	case "STRICT_RETURN":
		return CharterTypeStrictReturn, nil
	}
	var t CharterType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CharterType) Ptr() *CharterType {
	return &c
}
