// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
)

var (
	customerGetRequestFieldAppID = big.NewInt(1 << 0)
)

type CustomerGetRequest struct {
	// The App ID of the customer to get. If not provided, the ID of the calling app will be used.
	AppID *string `json:"-" url:"appId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CustomerGetRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerGetRequest) SetAppID(appID *string) {
	c.AppID = appID
	c.require(customerGetRequestFieldAppID)
}

var (
	customerBaseFieldName        = big.NewInt(1 << 0)
	customerBaseFieldDescription = big.NewInt(1 << 1)
	customerBaseFieldMetadata    = big.NewInt(1 << 2)
	customerBaseFieldStatus      = big.NewInt(1 << 3)
)

type CustomerBase struct {
	Name        string            `json:"name" url:"name"`
	Description *string           `json:"description,omitempty" url:"description,omitempty"`
	Metadata    map[string]string `json:"metadata" url:"metadata"`
	// Whether or not the customer is in active use.
	//
	// Only active customers will be available for agent interactions.
	Status CustomerStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerBase) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomerBase) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomerBase) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerBase) GetStatus() CustomerStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomerBase) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerBase) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerBase) SetName(name string) {
	c.Name = name
	c.require(customerBaseFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerBase) SetDescription(description *string) {
	c.Description = description
	c.require(customerBaseFieldDescription)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerBase) SetMetadata(metadata map[string]string) {
	c.Metadata = metadata
	c.require(customerBaseFieldMetadata)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerBase) SetStatus(status CustomerStatus) {
	c.Status = status
	c.require(customerBaseFieldStatus)
}

func (c *CustomerBase) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerBase
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerBase(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerBase) MarshalJSON() ([]byte, error) {
	type embed CustomerBase
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerBase) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerField string

const (
	CustomerFieldCreatedAt CustomerField = "CreatedAt"
	CustomerFieldName      CustomerField = "Name"
)

func NewCustomerFieldFromString(s string) (CustomerField, error) {
	switch s {
	case "CreatedAt":
		return CustomerFieldCreatedAt, nil
	case "Name":
		return CustomerFieldName, nil
	}
	var t CustomerField
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomerField) Ptr() *CustomerField {
	return &c
}

var (
	customerFilterFieldSearch    = big.NewInt(1 << 0)
	customerFilterFieldStatuses  = big.NewInt(1 << 1)
	customerFilterFieldAssignees = big.NewInt(1 << 2)
	customerFilterFieldMembers   = big.NewInt(1 << 3)
)

type CustomerFilter struct {
	// The search query to apply to the customers' name and description.
	Search *string `json:"search,omitempty" url:"search,omitempty"`
	// The statuses to filter the customers by.
	Statuses []CustomerStatus `json:"statuses,omitempty" url:"statuses,omitempty"`
	// Filter customers by assignee agent user IDs. Returns customers that have any of the specified assignees.
	Assignees []string `json:"assignees,omitempty" url:"assignees,omitempty"`
	// Filter customers by member agent user IDs. Returns customers that have any of the specified members.
	Members []string `json:"members,omitempty" url:"members,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerFilter) GetSearch() *string {
	if c == nil {
		return nil
	}
	return c.Search
}

func (c *CustomerFilter) GetStatuses() []CustomerStatus {
	if c == nil {
		return nil
	}
	return c.Statuses
}

func (c *CustomerFilter) GetAssignees() []string {
	if c == nil {
		return nil
	}
	return c.Assignees
}

func (c *CustomerFilter) GetMembers() []string {
	if c == nil {
		return nil
	}
	return c.Members
}

func (c *CustomerFilter) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerFilter) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerFilter) SetSearch(search *string) {
	c.Search = search
	c.require(customerFilterFieldSearch)
}

// SetStatuses sets the Statuses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerFilter) SetStatuses(statuses []CustomerStatus) {
	c.Statuses = statuses
	c.require(customerFilterFieldStatuses)
}

// SetAssignees sets the Assignees field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerFilter) SetAssignees(assignees []string) {
	c.Assignees = assignees
	c.require(customerFilterFieldAssignees)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerFilter) SetMembers(members []string) {
	c.Members = members
	c.require(customerFilterFieldMembers)
}

func (c *CustomerFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerFilter) MarshalJSON() ([]byte, error) {
	type embed CustomerFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerFilter) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customerPatchRequestFieldAppID       = big.NewInt(1 << 0)
	customerPatchRequestFieldName        = big.NewInt(1 << 1)
	customerPatchRequestFieldDescription = big.NewInt(1 << 2)
	customerPatchRequestFieldStatus      = big.NewInt(1 << 3)
	customerPatchRequestFieldMetadata    = big.NewInt(1 << 4)
	customerPatchRequestFieldAssignees   = big.NewInt(1 << 5)
	customerPatchRequestFieldMembers     = big.NewInt(1 << 6)
)

type CustomerPatchRequest struct {
	// The App ID of the customer to update. If not provided, the ID of the calling app will be used.
	AppID *string `json:"appId,omitempty" url:"appId,omitempty"`
	// The name of the customer.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The description of the customer.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Whether or not the customer is in active use.
	//
	// Only active customers will be available for agent interactions.
	Status *CustomerStatus `json:"status,omitempty" url:"status,omitempty"`
	// Metadata associated with the customer. If not provided, the existing metadata will be preserved.
	Metadata map[string]string `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Set of agent user IDs to assign to this customer. If provided, replaces all existing assignees.
	Assignees []string `json:"assignees,omitempty" url:"assignees,omitempty"`
	// Set of agent user IDs who are members of this customer. If provided, replaces all existing members.
	Members []string `json:"members,omitempty" url:"members,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerPatchRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CustomerPatchRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerPatchRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomerPatchRequest) GetStatus() *CustomerStatus {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CustomerPatchRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerPatchRequest) GetAssignees() []string {
	if c == nil {
		return nil
	}
	return c.Assignees
}

func (c *CustomerPatchRequest) GetMembers() []string {
	if c == nil {
		return nil
	}
	return c.Members
}

func (c *CustomerPatchRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerPatchRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetAppID(appID *string) {
	c.AppID = appID
	c.require(customerPatchRequestFieldAppID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetName(name *string) {
	c.Name = name
	c.require(customerPatchRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetDescription(description *string) {
	c.Description = description
	c.require(customerPatchRequestFieldDescription)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetStatus(status *CustomerStatus) {
	c.Status = status
	c.require(customerPatchRequestFieldStatus)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetMetadata(metadata map[string]string) {
	c.Metadata = metadata
	c.require(customerPatchRequestFieldMetadata)
}

// SetAssignees sets the Assignees field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetAssignees(assignees []string) {
	c.Assignees = assignees
	c.require(customerPatchRequestFieldAssignees)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerPatchRequest) SetMembers(members []string) {
	c.Members = members
	c.require(customerPatchRequestFieldMembers)
}

func (c *CustomerPatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerPatchRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerPatchRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerPatchRequest) MarshalJSON() ([]byte, error) {
	type embed CustomerPatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerPatchRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customerRequestFieldCustomerID = big.NewInt(1 << 0)
	customerRequestFieldName       = big.NewInt(1 << 1)
)

type CustomerRequest struct {
	// ID that uniquely identifies this customer
	CustomerID *EntityIDBase `json:"customerId" url:"customerId"`
	Name       string        `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerRequest) GetCustomerID() *EntityIDBase {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CustomerRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomerRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerRequest) SetCustomerID(customerID *EntityIDBase) {
	c.CustomerID = customerID
	c.require(customerRequestFieldCustomerID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerRequest) SetName(name string) {
	c.Name = name
	c.require(customerRequestFieldName)
}

func (c *CustomerRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerRequest) MarshalJSON() ([]byte, error) {
	type embed CustomerRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customerResponseFieldName        = big.NewInt(1 << 0)
	customerResponseFieldDescription = big.NewInt(1 << 1)
	customerResponseFieldMetadata    = big.NewInt(1 << 2)
	customerResponseFieldStatus      = big.NewInt(1 << 3)
	customerResponseFieldCustomerID  = big.NewInt(1 << 4)
	customerResponseFieldAssignees   = big.NewInt(1 << 5)
	customerResponseFieldMembers     = big.NewInt(1 << 6)
)

type CustomerResponse struct {
	Name        string            `json:"name" url:"name"`
	Description *string           `json:"description,omitempty" url:"description,omitempty"`
	Metadata    map[string]string `json:"metadata" url:"metadata"`
	// Whether or not the customer is in active use.
	//
	// Only active customers will be available for agent interactions.
	Status CustomerStatus `json:"status" url:"status"`
	// ID that uniquely identifies this customer
	CustomerID *EntityID `json:"customerId" url:"customerId"`
	// Set of agent user IDs assigned to this customer
	Assignees []string `json:"assignees" url:"assignees"`
	// Set of agent user IDs who are members of this customer
	Members []string `json:"members" url:"members"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomerResponse) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomerResponse) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerResponse) GetStatus() CustomerStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomerResponse) GetCustomerID() *EntityID {
	if c == nil {
		return nil
	}
	return c.CustomerID
}

func (c *CustomerResponse) GetAssignees() []string {
	if c == nil {
		return nil
	}
	return c.Assignees
}

func (c *CustomerResponse) GetMembers() []string {
	if c == nil {
		return nil
	}
	return c.Members
}

func (c *CustomerResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetName(name string) {
	c.Name = name
	c.require(customerResponseFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetDescription(description *string) {
	c.Description = description
	c.require(customerResponseFieldDescription)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetMetadata(metadata map[string]string) {
	c.Metadata = metadata
	c.require(customerResponseFieldMetadata)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetStatus(status CustomerStatus) {
	c.Status = status
	c.require(customerResponseFieldStatus)
}

// SetCustomerID sets the CustomerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetCustomerID(customerID *EntityID) {
	c.CustomerID = customerID
	c.require(customerResponseFieldCustomerID)
}

// SetAssignees sets the Assignees field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetAssignees(assignees []string) {
	c.Assignees = assignees
	c.require(customerResponseFieldAssignees)
}

// SetMembers sets the Members field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerResponse) SetMembers(members []string) {
	c.Members = members
	c.require(customerResponseFieldMembers)
}

func (c *CustomerResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerResponse) MarshalJSON() ([]byte, error) {
	type embed CustomerResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerStatus string

const (
	CustomerStatusActive   CustomerStatus = "ACTIVE"
	CustomerStatusInactive CustomerStatus = "INACTIVE"
)

func NewCustomerStatusFromString(s string) (CustomerStatus, error) {
	switch s {
	case "ACTIVE":
		return CustomerStatusActive, nil
	case "INACTIVE":
		return CustomerStatusInactive, nil
	}
	var t CustomerStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomerStatus) Ptr() *CustomerStatus {
	return &c
}

var (
	customersSearchRequestFieldPage     = big.NewInt(1 << 0)
	customersSearchRequestFieldSize     = big.NewInt(1 << 1)
	customersSearchRequestFieldSortDesc = big.NewInt(1 << 2)
	customersSearchRequestFieldSort     = big.NewInt(1 << 3)
	customersSearchRequestFieldFilter   = big.NewInt(1 << 4)
)

type CustomersSearchRequest struct {
	// Page number to return, defaults to 0
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// The size of the page to return, defaults to 20
	Size *int `json:"size,omitempty" url:"size,omitempty"`
	// Whether to sort descending, defaults to true
	SortDesc *bool `json:"sortDesc,omitempty" url:"sortDesc,omitempty"`
	// The field to sort by, defaults to created timestamp
	Sort *CustomerField `json:"sort,omitempty" url:"sort,omitempty"`
	// The filter to apply to the customers.
	Filter *CustomerFilter `json:"filter,omitempty" url:"filter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomersSearchRequest) GetPage() *int {
	if c == nil {
		return nil
	}
	return c.Page
}

func (c *CustomersSearchRequest) GetSize() *int {
	if c == nil {
		return nil
	}
	return c.Size
}

func (c *CustomersSearchRequest) GetSortDesc() *bool {
	if c == nil {
		return nil
	}
	return c.SortDesc
}

func (c *CustomersSearchRequest) GetSort() *CustomerField {
	if c == nil {
		return nil
	}
	return c.Sort
}

func (c *CustomersSearchRequest) GetFilter() *CustomerFilter {
	if c == nil {
		return nil
	}
	return c.Filter
}

func (c *CustomersSearchRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomersSearchRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchRequest) SetPage(page *int) {
	c.Page = page
	c.require(customersSearchRequestFieldPage)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchRequest) SetSize(size *int) {
	c.Size = size
	c.require(customersSearchRequestFieldSize)
}

// SetSortDesc sets the SortDesc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchRequest) SetSortDesc(sortDesc *bool) {
	c.SortDesc = sortDesc
	c.require(customersSearchRequestFieldSortDesc)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchRequest) SetSort(sort *CustomerField) {
	c.Sort = sort
	c.require(customersSearchRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchRequest) SetFilter(filter *CustomerFilter) {
	c.Filter = filter
	c.require(customersSearchRequestFieldFilter)
}

func (c *CustomersSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomersSearchRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomersSearchRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomersSearchRequest) MarshalJSON() ([]byte, error) {
	type embed CustomersSearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomersSearchRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customersSearchResponseFieldNumber        = big.NewInt(1 << 0)
	customersSearchResponseFieldSize          = big.NewInt(1 << 1)
	customersSearchResponseFieldTotalElements = big.NewInt(1 << 2)
	customersSearchResponseFieldTotalPages    = big.NewInt(1 << 3)
	customersSearchResponseFieldCustomers     = big.NewInt(1 << 4)
)

type CustomersSearchResponse struct {
	// The page being returned, starts at 0
	Number int `json:"number" url:"number"`
	// The number of elements in this page
	Size int `json:"size" url:"size"`
	// The total number of elements in the collection
	TotalElements int64 `json:"totalElements" url:"totalElements"`
	// The total number of pages in the collection
	TotalPages int                 `json:"totalPages" url:"totalPages"`
	Customers  []*CustomerResponse `json:"customers" url:"customers"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomersSearchResponse) GetNumber() int {
	if c == nil {
		return 0
	}
	return c.Number
}

func (c *CustomersSearchResponse) GetSize() int {
	if c == nil {
		return 0
	}
	return c.Size
}

func (c *CustomersSearchResponse) GetTotalElements() int64 {
	if c == nil {
		return 0
	}
	return c.TotalElements
}

func (c *CustomersSearchResponse) GetTotalPages() int {
	if c == nil {
		return 0
	}
	return c.TotalPages
}

func (c *CustomersSearchResponse) GetCustomers() []*CustomerResponse {
	if c == nil {
		return nil
	}
	return c.Customers
}

func (c *CustomersSearchResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomersSearchResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchResponse) SetNumber(number int) {
	c.Number = number
	c.require(customersSearchResponseFieldNumber)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchResponse) SetSize(size int) {
	c.Size = size
	c.require(customersSearchResponseFieldSize)
}

// SetTotalElements sets the TotalElements field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchResponse) SetTotalElements(totalElements int64) {
	c.TotalElements = totalElements
	c.require(customersSearchResponseFieldTotalElements)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchResponse) SetTotalPages(totalPages int) {
	c.TotalPages = totalPages
	c.require(customersSearchResponseFieldTotalPages)
}

// SetCustomers sets the Customers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomersSearchResponse) SetCustomers(customers []*CustomerResponse) {
	c.Customers = customers
	c.require(customersSearchResponseFieldCustomers)
}

func (c *CustomersSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomersSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomersSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomersSearchResponse) MarshalJSON() ([]byte, error) {
	type embed CustomersSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomersSearchResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
