// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &ServerError{
			APIError: apiError,
		}
	},
}
