// Code generated by Fern. DO NOT EDIT.

package api

import (
	big "math/big"
)

var (
	eventGetRequestFieldAppID = big.NewInt(1 << 0)
)

type EventGetRequest struct {
	// The App ID of the Event to retrieve
	AppID string `json:"-" url:"appId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (e *EventGetRequest) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventGetRequest) SetAppID(appID string) {
	e.AppID = appID
	e.require(eventGetRequestFieldAppID)
}
