// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
	time "time"
)

var (
	intelligentFieldDeleteRequestFieldAppID              = big.NewInt(1 << 0)
	intelligentFieldDeleteRequestFieldVariantReferenceID = big.NewInt(1 << 1)
	intelligentFieldDeleteRequestFieldVariantAppID       = big.NewInt(1 << 2)
)

type IntelligentFieldDeleteRequest struct {
	// The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.
	AppID *string `json:"-" url:"appId,omitempty"`
	// The agent variant reference ID of the intelligent field to delete.
	VariantReferenceID *string `json:"-" url:"variantReferenceId,omitempty"`
	// The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.
	VariantAppID *string `json:"-" url:"variantAppId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *IntelligentFieldDeleteRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDeleteRequest) SetAppID(appID *string) {
	i.AppID = appID
	i.require(intelligentFieldDeleteRequestFieldAppID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDeleteRequest) SetVariantReferenceID(variantReferenceID *string) {
	i.VariantReferenceID = variantReferenceID
	i.require(intelligentFieldDeleteRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDeleteRequest) SetVariantAppID(variantAppID *string) {
	i.VariantAppID = variantAppID
	i.require(intelligentFieldDeleteRequestFieldVariantAppID)
}

var (
	intelligentFieldGetRequestFieldAppID              = big.NewInt(1 << 0)
	intelligentFieldGetRequestFieldVariantReferenceID = big.NewInt(1 << 1)
	intelligentFieldGetRequestFieldVariantAppID       = big.NewInt(1 << 2)
)

type IntelligentFieldGetRequest struct {
	// The App ID of the intelligent field to get. If not provided the ID of the calling app will be used.
	AppID *string `json:"-" url:"appId,omitempty"`
	// The agent variant reference ID to resolve the intelligent field's version through. If not provided, defaults to the agent's production variant.
	VariantReferenceID *string `json:"-" url:"variantReferenceId,omitempty"`
	// The App ID of the agent variant reference. If not provided, the ID of the calling app will be used.
	VariantAppID *string `json:"-" url:"variantAppId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *IntelligentFieldGetRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldGetRequest) SetAppID(appID *string) {
	i.AppID = appID
	i.require(intelligentFieldGetRequestFieldAppID)
}

// SetVariantReferenceID sets the VariantReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldGetRequest) SetVariantReferenceID(variantReferenceID *string) {
	i.VariantReferenceID = variantReferenceID
	i.require(intelligentFieldGetRequestFieldVariantReferenceID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldGetRequest) SetVariantAppID(variantAppID *string) {
	i.VariantAppID = variantAppID
	i.require(intelligentFieldGetRequestFieldVariantAppID)
}

var (
	intelligentFieldPatchRequestFieldAppID        = big.NewInt(1 << 0)
	intelligentFieldPatchRequestFieldDefinition   = big.NewInt(1 << 1)
	intelligentFieldPatchRequestFieldStatus       = big.NewInt(1 << 2)
	intelligentFieldPatchRequestFieldDescription  = big.NewInt(1 << 3)
	intelligentFieldPatchRequestFieldEnumOptions  = big.NewInt(1 << 4)
	intelligentFieldPatchRequestFieldVariantID    = big.NewInt(1 << 5)
	intelligentFieldPatchRequestFieldVariantAppID = big.NewInt(1 << 6)
)

type IntelligentFieldPatchRequest struct {
	// The App ID of the intelligent field to update. If not provided the ID of the calling app will be used.
	AppID *string `json:"appId,omitempty" url:"-"`
	// The definition of the intelligent field. This text will be influential in guiding the LLM to produce the desired results. Limited to 5,000 characters.
	Definition *string `json:"definition,omitempty" url:"-"`
	// The lifecycle state for whether this field is evaluated. Use ACTIVE to start
	// evaluating the field and INACTIVE to stop.
	//
	// Each agent has a limit on how many fields may be ACTIVE at once; activating a
	// field beyond that limit is rejected. A field referenced by an active precondition
	// cannot be deactivated.
	Status *IntelligentFieldStatus `json:"status,omitempty" url:"-"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"-"`
	// Updated enum options for fields that constrain the LLM to a finite set. Omit to leave unchanged. The new list must be a superset of the existing options (add-only; removals are rejected).
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"-"`
	// The agent variant to stage this patch in, by reference ID. Its owning app is `variantAppId`.
	VariantID *EntityIDBase `json:"variantId,omitempty" url:"-"`
	// The App ID of the agent variant named by `variantId`. If not provided, the ID of the calling app will be used — name the owning app to patch in a variant the caller does not own, as the platform's own seeded variants are.
	VariantAppID *string `json:"variantAppId,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *IntelligentFieldPatchRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAppID sets the AppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetAppID(appID *string) {
	i.AppID = appID
	i.require(intelligentFieldPatchRequestFieldAppID)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetDefinition(definition *string) {
	i.Definition = definition
	i.require(intelligentFieldPatchRequestFieldDefinition)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetStatus(status *IntelligentFieldStatus) {
	i.Status = status
	i.require(intelligentFieldPatchRequestFieldStatus)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldPatchRequestFieldDescription)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldPatchRequestFieldEnumOptions)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetVariantID(variantID *EntityIDBase) {
	i.VariantID = variantID
	i.require(intelligentFieldPatchRequestFieldVariantID)
}

// SetVariantAppID sets the VariantAppID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldPatchRequest) SetVariantAppID(variantAppID *string) {
	i.VariantAppID = variantAppID
	i.require(intelligentFieldPatchRequestFieldVariantAppID)
}

// One allowed choice for a field whose value should come from a finite set. Use with
// MULTI_SELECT to constrain a list of choices, or with STRING/MULTILINE/NUMBER to make
// the field a single select.
var (
	enumOptionFieldValue = big.NewInt(1 << 0)
	enumOptionFieldLabel = big.NewInt(1 << 1)
)

type EnumOption struct {
	// The value of the option
	Value string `json:"value" url:"value"`
	// Display label for the option
	Label *string `json:"label,omitempty" url:"label,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EnumOption) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}

func (e *EnumOption) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnumOption) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EnumOption) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EnumOption) SetValue(value string) {
	e.Value = value
	e.require(enumOptionFieldValue)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EnumOption) SetLabel(label *string) {
	e.Label = label
	e.require(enumOptionFieldLabel)
}

func (e *EnumOption) UnmarshalJSON(data []byte) error {
	type unmarshaler EnumOption
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EnumOption(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EnumOption) MarshalJSON() ([]byte, error) {
	type embed EnumOption
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EnumOption) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	intelligentFieldBaseFieldName           = big.NewInt(1 << 0)
	intelligentFieldBaseFieldDescription    = big.NewInt(1 << 1)
	intelligentFieldBaseFieldValidationType = big.NewInt(1 << 2)
	intelligentFieldBaseFieldDefinition     = big.NewInt(1 << 3)
	intelligentFieldBaseFieldEnumOptions    = big.NewInt(1 << 4)
	intelligentFieldBaseFieldEntityType     = big.NewInt(1 << 5)
	intelligentFieldBaseFieldVariantID      = big.NewInt(1 << 6)
)

type IntelligentFieldBase struct {
	// Display name for the intelligent field
	Name string `json:"name" url:"name"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The type of value this field holds. It constrains the schema the LLM is asked to fill
	// and the JSON type of the computed `value`.
	//
	// - STRING / MULTILINE: a single string
	// - MULTI_SELECT: a list of strings
	// - BOOLEAN: `true` or `false`
	// - NUMBER: a number
	//
	// For a single select, use STRING or NUMBER together with `enumOptions`.
	ValidationType IntelligentFieldType `json:"validationType" url:"validationType"`
	// Definition used by the LLM when generating this field's value
	Definition string `json:"definition" url:"definition"`
	// The finite set of values this field may take. Omit to let the LLM produce any value of
	// the `validationType`. Options may be added later with the patch endpoint, but not removed.
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"enumOptions,omitempty"`
	// Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.
	EntityType EntityType `json:"entityType" url:"entityType"`
	// ID of the agent variant this field belongs to, if applicable
	VariantID *EntityIDWithoutAgent `json:"variantId,omitempty" url:"variantId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldBase) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntelligentFieldBase) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntelligentFieldBase) GetValidationType() IntelligentFieldType {
	if i == nil {
		return ""
	}
	return i.ValidationType
}

func (i *IntelligentFieldBase) GetDefinition() string {
	if i == nil {
		return ""
	}
	return i.Definition
}

func (i *IntelligentFieldBase) GetEnumOptions() []*EnumOption {
	if i == nil {
		return nil
	}
	return i.EnumOptions
}

func (i *IntelligentFieldBase) GetEntityType() EntityType {
	if i == nil {
		return ""
	}
	return i.EntityType
}

func (i *IntelligentFieldBase) GetVariantID() *EntityIDWithoutAgent {
	if i == nil {
		return nil
	}
	return i.VariantID
}

func (i *IntelligentFieldBase) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldBase) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetName(name string) {
	i.Name = name
	i.require(intelligentFieldBaseFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldBaseFieldDescription)
}

// SetValidationType sets the ValidationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetValidationType(validationType IntelligentFieldType) {
	i.ValidationType = validationType
	i.require(intelligentFieldBaseFieldValidationType)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetDefinition(definition string) {
	i.Definition = definition
	i.require(intelligentFieldBaseFieldDefinition)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldBaseFieldEnumOptions)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetEntityType(entityType EntityType) {
	i.EntityType = entityType
	i.require(intelligentFieldBaseFieldEntityType)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldBase) SetVariantID(variantID *EntityIDWithoutAgent) {
	i.VariantID = variantID
	i.require(intelligentFieldBaseFieldVariantID)
}

func (i *IntelligentFieldBase) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldBase
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldBase(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldBase) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldBase
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldBase) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The content of an intelligent field -- what it is called, and what the LLM should produce for it.
var (
	intelligentFieldCoreFieldName           = big.NewInt(1 << 0)
	intelligentFieldCoreFieldDescription    = big.NewInt(1 << 1)
	intelligentFieldCoreFieldValidationType = big.NewInt(1 << 2)
	intelligentFieldCoreFieldDefinition     = big.NewInt(1 << 3)
	intelligentFieldCoreFieldEnumOptions    = big.NewInt(1 << 4)
)

type IntelligentFieldCore struct {
	// Display name for the intelligent field
	Name string `json:"name" url:"name"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The type of value this field holds. It constrains the schema the LLM is asked to fill
	// and the JSON type of the computed `value`.
	//
	// - STRING / MULTILINE: a single string
	// - MULTI_SELECT: a list of strings
	// - BOOLEAN: `true` or `false`
	// - NUMBER: a number
	//
	// For a single select, use STRING or NUMBER together with `enumOptions`.
	ValidationType IntelligentFieldType `json:"validationType" url:"validationType"`
	// Definition used by the LLM when generating this field's value
	Definition string `json:"definition" url:"definition"`
	// The finite set of values this field may take. Omit to let the LLM produce any value of
	// the `validationType`. Options may be added later with the patch endpoint, but not removed.
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"enumOptions,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldCore) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntelligentFieldCore) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntelligentFieldCore) GetValidationType() IntelligentFieldType {
	if i == nil {
		return ""
	}
	return i.ValidationType
}

func (i *IntelligentFieldCore) GetDefinition() string {
	if i == nil {
		return ""
	}
	return i.Definition
}

func (i *IntelligentFieldCore) GetEnumOptions() []*EnumOption {
	if i == nil {
		return nil
	}
	return i.EnumOptions
}

func (i *IntelligentFieldCore) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldCore) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldCore) SetName(name string) {
	i.Name = name
	i.require(intelligentFieldCoreFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldCore) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldCoreFieldDescription)
}

// SetValidationType sets the ValidationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldCore) SetValidationType(validationType IntelligentFieldType) {
	i.ValidationType = validationType
	i.require(intelligentFieldCoreFieldValidationType)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldCore) SetDefinition(definition string) {
	i.Definition = definition
	i.require(intelligentFieldCoreFieldDefinition)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldCore) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldCoreFieldEnumOptions)
}

func (i *IntelligentFieldCore) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldCore
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldCore(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldCore) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldCore
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldCore) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	intelligentFieldDetailResponseFieldName                = big.NewInt(1 << 0)
	intelligentFieldDetailResponseFieldDescription         = big.NewInt(1 << 1)
	intelligentFieldDetailResponseFieldValidationType      = big.NewInt(1 << 2)
	intelligentFieldDetailResponseFieldDefinition          = big.NewInt(1 << 3)
	intelligentFieldDetailResponseFieldEnumOptions         = big.NewInt(1 << 4)
	intelligentFieldDetailResponseFieldEntityType          = big.NewInt(1 << 5)
	intelligentFieldDetailResponseFieldVariantID           = big.NewInt(1 << 6)
	intelligentFieldDetailResponseFieldFieldID             = big.NewInt(1 << 7)
	intelligentFieldDetailResponseFieldStatus              = big.NewInt(1 << 8)
	intelligentFieldDetailResponseFieldCreatedAt           = big.NewInt(1 << 9)
	intelligentFieldDetailResponseFieldUpdatedAt           = big.NewInt(1 << 10)
	intelligentFieldDetailResponseFieldReferencingCharters = big.NewInt(1 << 11)
)

type IntelligentFieldDetailResponse struct {
	// Display name for the intelligent field
	Name string `json:"name" url:"name"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The type of value this field holds. It constrains the schema the LLM is asked to fill
	// and the JSON type of the computed `value`.
	//
	// - STRING / MULTILINE: a single string
	// - MULTI_SELECT: a list of strings
	// - BOOLEAN: `true` or `false`
	// - NUMBER: a number
	//
	// For a single select, use STRING or NUMBER together with `enumOptions`.
	ValidationType IntelligentFieldType `json:"validationType" url:"validationType"`
	// Definition used by the LLM when generating this field's value
	Definition string `json:"definition" url:"definition"`
	// The finite set of values this field may take. Omit to let the LLM produce any value of
	// the `validationType`. Options may be added later with the patch endpoint, but not removed.
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"enumOptions,omitempty"`
	// Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.
	EntityType EntityType `json:"entityType" url:"entityType"`
	// ID of the agent variant this field belongs to, if applicable
	VariantID *EntityIDWithoutAgent `json:"variantId,omitempty" url:"variantId,omitempty"`
	// ID that uniquely identifies this intelligent field
	FieldID *EntityID `json:"fieldId" url:"fieldId"`
	// Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.
	Status IntelligentFieldStatus `json:"status" url:"status"`
	// The date and time the intelligent field was created
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// The date and time the intelligent field was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	// Charters whose precondition references this intelligent field. A field referenced by
	// an active precondition cannot be deactivated.
	ReferencingCharters []*CharterSummary `json:"referencingCharters,omitempty" url:"referencingCharters,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldDetailResponse) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntelligentFieldDetailResponse) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntelligentFieldDetailResponse) GetValidationType() IntelligentFieldType {
	if i == nil {
		return ""
	}
	return i.ValidationType
}

func (i *IntelligentFieldDetailResponse) GetDefinition() string {
	if i == nil {
		return ""
	}
	return i.Definition
}

func (i *IntelligentFieldDetailResponse) GetEnumOptions() []*EnumOption {
	if i == nil {
		return nil
	}
	return i.EnumOptions
}

func (i *IntelligentFieldDetailResponse) GetEntityType() EntityType {
	if i == nil {
		return ""
	}
	return i.EntityType
}

func (i *IntelligentFieldDetailResponse) GetVariantID() *EntityIDWithoutAgent {
	if i == nil {
		return nil
	}
	return i.VariantID
}

func (i *IntelligentFieldDetailResponse) GetFieldID() *EntityID {
	if i == nil {
		return nil
	}
	return i.FieldID
}

func (i *IntelligentFieldDetailResponse) GetStatus() IntelligentFieldStatus {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IntelligentFieldDetailResponse) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *IntelligentFieldDetailResponse) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *IntelligentFieldDetailResponse) GetReferencingCharters() []*CharterSummary {
	if i == nil {
		return nil
	}
	return i.ReferencingCharters
}

func (i *IntelligentFieldDetailResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldDetailResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetName(name string) {
	i.Name = name
	i.require(intelligentFieldDetailResponseFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldDetailResponseFieldDescription)
}

// SetValidationType sets the ValidationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetValidationType(validationType IntelligentFieldType) {
	i.ValidationType = validationType
	i.require(intelligentFieldDetailResponseFieldValidationType)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetDefinition(definition string) {
	i.Definition = definition
	i.require(intelligentFieldDetailResponseFieldDefinition)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldDetailResponseFieldEnumOptions)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetEntityType(entityType EntityType) {
	i.EntityType = entityType
	i.require(intelligentFieldDetailResponseFieldEntityType)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetVariantID(variantID *EntityIDWithoutAgent) {
	i.VariantID = variantID
	i.require(intelligentFieldDetailResponseFieldVariantID)
}

// SetFieldID sets the FieldID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetFieldID(fieldID *EntityID) {
	i.FieldID = fieldID
	i.require(intelligentFieldDetailResponseFieldFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetStatus(status IntelligentFieldStatus) {
	i.Status = status
	i.require(intelligentFieldDetailResponseFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetCreatedAt(createdAt *time.Time) {
	i.CreatedAt = createdAt
	i.require(intelligentFieldDetailResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetUpdatedAt(updatedAt *time.Time) {
	i.UpdatedAt = updatedAt
	i.require(intelligentFieldDetailResponseFieldUpdatedAt)
}

// SetReferencingCharters sets the ReferencingCharters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldDetailResponse) SetReferencingCharters(referencingCharters []*CharterSummary) {
	i.ReferencingCharters = referencingCharters
	i.require(intelligentFieldDetailResponseFieldReferencingCharters)
}

func (i *IntelligentFieldDetailResponse) UnmarshalJSON(data []byte) error {
	type embed IntelligentFieldDetailResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IntelligentFieldDetailResponse(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	i.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldDetailResponse) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldDetailResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewOptionalDateTime(i.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(i.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldDetailResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	intelligentFieldRequestFieldName           = big.NewInt(1 << 0)
	intelligentFieldRequestFieldDescription    = big.NewInt(1 << 1)
	intelligentFieldRequestFieldValidationType = big.NewInt(1 << 2)
	intelligentFieldRequestFieldDefinition     = big.NewInt(1 << 3)
	intelligentFieldRequestFieldEnumOptions    = big.NewInt(1 << 4)
	intelligentFieldRequestFieldEntityType     = big.NewInt(1 << 5)
	intelligentFieldRequestFieldVariantID      = big.NewInt(1 << 6)
	intelligentFieldRequestFieldFieldID        = big.NewInt(1 << 7)
)

type IntelligentFieldRequest struct {
	// Display name for the intelligent field
	Name string `json:"name" url:"name"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The type of value this field holds. It constrains the schema the LLM is asked to fill
	// and the JSON type of the computed `value`.
	//
	// - STRING / MULTILINE: a single string
	// - MULTI_SELECT: a list of strings
	// - BOOLEAN: `true` or `false`
	// - NUMBER: a number
	//
	// For a single select, use STRING or NUMBER together with `enumOptions`.
	ValidationType IntelligentFieldType `json:"validationType" url:"validationType"`
	// Definition used by the LLM when generating this field's value
	Definition string `json:"definition" url:"definition"`
	// The finite set of values this field may take. Omit to let the LLM produce any value of
	// the `validationType`. Options may be added later with the patch endpoint, but not removed.
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"enumOptions,omitempty"`
	// Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.
	EntityType EntityType `json:"entityType" url:"entityType"`
	// ID of the agent variant this field belongs to, if applicable
	VariantID *EntityIDWithoutAgent `json:"variantId,omitempty" url:"variantId,omitempty"`
	// ID that uniquely identifies this intelligent field. `referenceId` is supplied by the
	// caller and is how the field is addressed on every other endpoint.
	FieldID *EntityIDBase `json:"fieldId" url:"fieldId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldRequest) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntelligentFieldRequest) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntelligentFieldRequest) GetValidationType() IntelligentFieldType {
	if i == nil {
		return ""
	}
	return i.ValidationType
}

func (i *IntelligentFieldRequest) GetDefinition() string {
	if i == nil {
		return ""
	}
	return i.Definition
}

func (i *IntelligentFieldRequest) GetEnumOptions() []*EnumOption {
	if i == nil {
		return nil
	}
	return i.EnumOptions
}

func (i *IntelligentFieldRequest) GetEntityType() EntityType {
	if i == nil {
		return ""
	}
	return i.EntityType
}

func (i *IntelligentFieldRequest) GetVariantID() *EntityIDWithoutAgent {
	if i == nil {
		return nil
	}
	return i.VariantID
}

func (i *IntelligentFieldRequest) GetFieldID() *EntityIDBase {
	if i == nil {
		return nil
	}
	return i.FieldID
}

func (i *IntelligentFieldRequest) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetName(name string) {
	i.Name = name
	i.require(intelligentFieldRequestFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldRequestFieldDescription)
}

// SetValidationType sets the ValidationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetValidationType(validationType IntelligentFieldType) {
	i.ValidationType = validationType
	i.require(intelligentFieldRequestFieldValidationType)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetDefinition(definition string) {
	i.Definition = definition
	i.require(intelligentFieldRequestFieldDefinition)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldRequestFieldEnumOptions)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetEntityType(entityType EntityType) {
	i.EntityType = entityType
	i.require(intelligentFieldRequestFieldEntityType)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetVariantID(variantID *EntityIDWithoutAgent) {
	i.VariantID = variantID
	i.require(intelligentFieldRequestFieldVariantID)
}

// SetFieldID sets the FieldID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldRequest) SetFieldID(fieldID *EntityIDBase) {
	i.FieldID = fieldID
	i.require(intelligentFieldRequestFieldFieldID)
}

func (i *IntelligentFieldRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldRequest) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldRequest) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	intelligentFieldResponseFieldName           = big.NewInt(1 << 0)
	intelligentFieldResponseFieldDescription    = big.NewInt(1 << 1)
	intelligentFieldResponseFieldValidationType = big.NewInt(1 << 2)
	intelligentFieldResponseFieldDefinition     = big.NewInt(1 << 3)
	intelligentFieldResponseFieldEnumOptions    = big.NewInt(1 << 4)
	intelligentFieldResponseFieldEntityType     = big.NewInt(1 << 5)
	intelligentFieldResponseFieldVariantID      = big.NewInt(1 << 6)
	intelligentFieldResponseFieldFieldID        = big.NewInt(1 << 7)
	intelligentFieldResponseFieldStatus         = big.NewInt(1 << 8)
	intelligentFieldResponseFieldCreatedAt      = big.NewInt(1 << 9)
	intelligentFieldResponseFieldUpdatedAt      = big.NewInt(1 << 10)
)

type IntelligentFieldResponse struct {
	// Display name for the intelligent field
	Name string `json:"name" url:"name"`
	// A plain text description of the intelligent field.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The type of value this field holds. It constrains the schema the LLM is asked to fill
	// and the JSON type of the computed `value`.
	//
	// - STRING / MULTILINE: a single string
	// - MULTI_SELECT: a list of strings
	// - BOOLEAN: `true` or `false`
	// - NUMBER: a number
	//
	// For a single select, use STRING or NUMBER together with `enumOptions`.
	ValidationType IntelligentFieldType `json:"validationType" url:"validationType"`
	// Definition used by the LLM when generating this field's value
	Definition string `json:"definition" url:"definition"`
	// The finite set of values this field may take. Omit to let the LLM produce any value of
	// the `validationType`. Options may be added later with the patch endpoint, but not removed.
	EnumOptions []*EnumOption `json:"enumOptions,omitempty" url:"enumOptions,omitempty"`
	// Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.
	EntityType EntityType `json:"entityType" url:"entityType"`
	// ID of the agent variant this field belongs to, if applicable
	VariantID *EntityIDWithoutAgent `json:"variantId,omitempty" url:"variantId,omitempty"`
	// ID that uniquely identifies this intelligent field
	FieldID *EntityID `json:"fieldId" url:"fieldId"`
	// Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.
	Status IntelligentFieldStatus `json:"status" url:"status"`
	// The date and time the intelligent field was created
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// The date and time the intelligent field was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldResponse) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntelligentFieldResponse) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntelligentFieldResponse) GetValidationType() IntelligentFieldType {
	if i == nil {
		return ""
	}
	return i.ValidationType
}

func (i *IntelligentFieldResponse) GetDefinition() string {
	if i == nil {
		return ""
	}
	return i.Definition
}

func (i *IntelligentFieldResponse) GetEnumOptions() []*EnumOption {
	if i == nil {
		return nil
	}
	return i.EnumOptions
}

func (i *IntelligentFieldResponse) GetEntityType() EntityType {
	if i == nil {
		return ""
	}
	return i.EntityType
}

func (i *IntelligentFieldResponse) GetVariantID() *EntityIDWithoutAgent {
	if i == nil {
		return nil
	}
	return i.VariantID
}

func (i *IntelligentFieldResponse) GetFieldID() *EntityID {
	if i == nil {
		return nil
	}
	return i.FieldID
}

func (i *IntelligentFieldResponse) GetStatus() IntelligentFieldStatus {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IntelligentFieldResponse) GetCreatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *IntelligentFieldResponse) GetUpdatedAt() *time.Time {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *IntelligentFieldResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetName(name string) {
	i.Name = name
	i.require(intelligentFieldResponseFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetDescription(description *string) {
	i.Description = description
	i.require(intelligentFieldResponseFieldDescription)
}

// SetValidationType sets the ValidationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetValidationType(validationType IntelligentFieldType) {
	i.ValidationType = validationType
	i.require(intelligentFieldResponseFieldValidationType)
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetDefinition(definition string) {
	i.Definition = definition
	i.require(intelligentFieldResponseFieldDefinition)
}

// SetEnumOptions sets the EnumOptions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetEnumOptions(enumOptions []*EnumOption) {
	i.EnumOptions = enumOptions
	i.require(intelligentFieldResponseFieldEnumOptions)
}

// SetEntityType sets the EntityType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetEntityType(entityType EntityType) {
	i.EntityType = entityType
	i.require(intelligentFieldResponseFieldEntityType)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetVariantID(variantID *EntityIDWithoutAgent) {
	i.VariantID = variantID
	i.require(intelligentFieldResponseFieldVariantID)
}

// SetFieldID sets the FieldID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetFieldID(fieldID *EntityID) {
	i.FieldID = fieldID
	i.require(intelligentFieldResponseFieldFieldID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetStatus(status IntelligentFieldStatus) {
	i.Status = status
	i.require(intelligentFieldResponseFieldStatus)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetCreatedAt(createdAt *time.Time) {
	i.CreatedAt = createdAt
	i.require(intelligentFieldResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldResponse) SetUpdatedAt(updatedAt *time.Time) {
	i.UpdatedAt = updatedAt
	i.require(intelligentFieldResponseFieldUpdatedAt)
}

func (i *IntelligentFieldResponse) UnmarshalJSON(data []byte) error {
	type embed IntelligentFieldResponse
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IntelligentFieldResponse(unmarshaler.embed)
	i.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	i.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldResponse) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldResponse
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed:     embed(*i),
		CreatedAt: internal.NewOptionalDateTime(i.CreatedAt),
		UpdatedAt: internal.NewOptionalDateTime(i.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Lifecycle state for whether this field is evaluated
type IntelligentFieldStatus string

const (
	// The field is evaluated, and values are computed for matching entities.
	IntelligentFieldStatusActive IntelligentFieldStatus = "ACTIVE"
	// The field exists but is not evaluated. This is the state a new field is created in.
	IntelligentFieldStatusInactive IntelligentFieldStatus = "INACTIVE"
	// The field has been soft deleted and cannot be modified. Set by the delete endpoint
	// rather than by a patch.
	IntelligentFieldStatusDeleted IntelligentFieldStatus = "DELETED"
)

func NewIntelligentFieldStatusFromString(s string) (IntelligentFieldStatus, error) {
	switch s {
	case "ACTIVE":
		return IntelligentFieldStatusActive, nil
	case "INACTIVE":
		return IntelligentFieldStatusInactive, nil
	case "DELETED":
		return IntelligentFieldStatusDeleted, nil
	}
	var t IntelligentFieldStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntelligentFieldStatus) Ptr() *IntelligentFieldStatus {
	return &i
}

// Result type hint used for schema generation, UI, and validation
type IntelligentFieldType string

const (
	// A single short string value.
	IntelligentFieldTypeString IntelligentFieldType = "STRING"
	// A single string value expected to run to several lines, such as a summary.
	IntelligentFieldTypeMultiline IntelligentFieldType = "MULTILINE"
	// A list of string values, normally paired with `enumOptions` to constrain the choices.
	IntelligentFieldTypeMultiSelect IntelligentFieldType = "MULTI_SELECT"
	// A true/false value.
	IntelligentFieldTypeBoolean IntelligentFieldType = "BOOLEAN"
	// A numeric value.
	IntelligentFieldTypeNumber IntelligentFieldType = "NUMBER"
)

func NewIntelligentFieldTypeFromString(s string) (IntelligentFieldType, error) {
	switch s {
	case "STRING":
		return IntelligentFieldTypeString, nil
	case "MULTILINE":
		return IntelligentFieldTypeMultiline, nil
	case "MULTI_SELECT":
		return IntelligentFieldTypeMultiSelect, nil
	case "BOOLEAN":
		return IntelligentFieldTypeBoolean, nil
	case "NUMBER":
		return IntelligentFieldTypeNumber, nil
	}
	var t IntelligentFieldType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntelligentFieldType) Ptr() *IntelligentFieldType {
	return &i
}

// Filter by properties of the target entity
var (
	intelligentFieldValueEntityFilterFieldEntityIDs = big.NewInt(1 << 0)
)

type IntelligentFieldValueEntityFilter struct {
	// Filter to specific target entities by their entity IDs. OR semantics. Maximum 100 IDs.
	EntityIDs []*EntityID `json:"entityIds,omitempty" url:"entityIds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldValueEntityFilter) GetEntityIDs() []*EntityID {
	if i == nil {
		return nil
	}
	return i.EntityIDs
}

func (i *IntelligentFieldValueEntityFilter) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldValueEntityFilter) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetEntityIDs sets the EntityIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueEntityFilter) SetEntityIDs(entityIDs []*EntityID) {
	i.EntityIDs = entityIDs
	i.require(intelligentFieldValueEntityFilterFieldEntityIDs)
}

func (i *IntelligentFieldValueEntityFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldValueEntityFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldValueEntityFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldValueEntityFilter) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldValueEntityFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldValueEntityFilter) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Filter by properties of the intelligent field definition
var (
	intelligentFieldValueFieldFilterFieldFieldIDs        = big.NewInt(1 << 0)
	intelligentFieldValueFieldFilterFieldValidationTypes = big.NewInt(1 << 1)
)

type IntelligentFieldValueFieldFilter struct {
	// Filter to specific fields by their entity IDs. OR semantics. Maximum 100 IDs.
	FieldIDs []*EntityID `json:"fieldIds,omitempty" url:"fieldIds,omitempty"`
	// Filter by field validation type (STRING, MULTILINE, MULTI_SELECT, BOOLEAN, NUMBER). OR semantics.
	ValidationTypes []IntelligentFieldType `json:"validationTypes,omitempty" url:"validationTypes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldValueFieldFilter) GetFieldIDs() []*EntityID {
	if i == nil {
		return nil
	}
	return i.FieldIDs
}

func (i *IntelligentFieldValueFieldFilter) GetValidationTypes() []IntelligentFieldType {
	if i == nil {
		return nil
	}
	return i.ValidationTypes
}

func (i *IntelligentFieldValueFieldFilter) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldValueFieldFilter) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetFieldIDs sets the FieldIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueFieldFilter) SetFieldIDs(fieldIDs []*EntityID) {
	i.FieldIDs = fieldIDs
	i.require(intelligentFieldValueFieldFilterFieldFieldIDs)
}

// SetValidationTypes sets the ValidationTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueFieldFilter) SetValidationTypes(validationTypes []IntelligentFieldType) {
	i.ValidationTypes = validationTypes
	i.require(intelligentFieldValueFieldFilterFieldValidationTypes)
}

func (i *IntelligentFieldValueFieldFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldValueFieldFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldValueFieldFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldValueFieldFilter) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldValueFieldFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldValueFieldFilter) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	intelligentFieldValueSearchRequestFieldPage                 = big.NewInt(1 << 0)
	intelligentFieldValueSearchRequestFieldSize                 = big.NewInt(1 << 1)
	intelligentFieldValueSearchRequestFieldSortDesc             = big.NewInt(1 << 2)
	intelligentFieldValueSearchRequestFieldFieldFilter          = big.NewInt(1 << 3)
	intelligentFieldValueSearchRequestFieldEntityFilter         = big.NewInt(1 << 4)
	intelligentFieldValueSearchRequestFieldCreatedAfter         = big.NewInt(1 << 5)
	intelligentFieldValueSearchRequestFieldCreatedBefore        = big.NewInt(1 << 6)
	intelligentFieldValueSearchRequestFieldIncludeUnknownValues = big.NewInt(1 << 7)
	intelligentFieldValueSearchRequestFieldSort                 = big.NewInt(1 << 8)
	intelligentFieldValueSearchRequestFieldVariantID            = big.NewInt(1 << 9)
)

type IntelligentFieldValueSearchRequest struct {
	// Page number to return, defaults to 0
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// The size of the page to return, defaults to 20. Max 1000.
	Size *int `json:"size,omitempty" url:"size,omitempty"`
	// Whether to sort descending, defaults to true
	SortDesc *bool `json:"sortDesc,omitempty" url:"sortDesc,omitempty"`
	// Filter by properties of the intelligent field definition. If not provided, returns values for all fields.
	FieldFilter *IntelligentFieldValueFieldFilter `json:"fieldFilter,omitempty" url:"fieldFilter,omitempty"`
	// Filter by properties of the target entity. If not provided, returns values across all entities.
	EntityFilter *IntelligentFieldValueEntityFilter `json:"entityFilter,omitempty" url:"entityFilter,omitempty"`
	// Filter values computed on or after this timestamp
	CreatedAfter *time.Time `json:"createdAfter,omitempty" url:"createdAfter,omitempty"`
	// Filter values computed on or before this timestamp
	CreatedBefore *time.Time `json:"createdBefore,omitempty" url:"createdBefore,omitempty"`
	// Whether to include results where the LLM could not determine a value (value is null). Defaults to false.
	IncludeUnknownValues *bool `json:"includeUnknownValues,omitempty" url:"includeUnknownValues,omitempty"`
	// Field to sort by. Defaults to CREATED_AT.
	Sort *IntelligentFieldValueSortField `json:"sort,omitempty" url:"sort,omitempty"`
	// Filter to values generated by a specific agent variant. If not provided, returns values from all variants.
	VariantID *EntityIDWithoutAgent `json:"variantId,omitempty" url:"variantId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldValueSearchRequest) GetPage() *int {
	if i == nil {
		return nil
	}
	return i.Page
}

func (i *IntelligentFieldValueSearchRequest) GetSize() *int {
	if i == nil {
		return nil
	}
	return i.Size
}

func (i *IntelligentFieldValueSearchRequest) GetSortDesc() *bool {
	if i == nil {
		return nil
	}
	return i.SortDesc
}

func (i *IntelligentFieldValueSearchRequest) GetFieldFilter() *IntelligentFieldValueFieldFilter {
	if i == nil {
		return nil
	}
	return i.FieldFilter
}

func (i *IntelligentFieldValueSearchRequest) GetEntityFilter() *IntelligentFieldValueEntityFilter {
	if i == nil {
		return nil
	}
	return i.EntityFilter
}

func (i *IntelligentFieldValueSearchRequest) GetCreatedAfter() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedAfter
}

func (i *IntelligentFieldValueSearchRequest) GetCreatedBefore() *time.Time {
	if i == nil {
		return nil
	}
	return i.CreatedBefore
}

func (i *IntelligentFieldValueSearchRequest) GetIncludeUnknownValues() *bool {
	if i == nil {
		return nil
	}
	return i.IncludeUnknownValues
}

func (i *IntelligentFieldValueSearchRequest) GetSort() *IntelligentFieldValueSortField {
	if i == nil {
		return nil
	}
	return i.Sort
}

func (i *IntelligentFieldValueSearchRequest) GetVariantID() *EntityIDWithoutAgent {
	if i == nil {
		return nil
	}
	return i.VariantID
}

func (i *IntelligentFieldValueSearchRequest) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldValueSearchRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetPage(page *int) {
	i.Page = page
	i.require(intelligentFieldValueSearchRequestFieldPage)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetSize(size *int) {
	i.Size = size
	i.require(intelligentFieldValueSearchRequestFieldSize)
}

// SetSortDesc sets the SortDesc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetSortDesc(sortDesc *bool) {
	i.SortDesc = sortDesc
	i.require(intelligentFieldValueSearchRequestFieldSortDesc)
}

// SetFieldFilter sets the FieldFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetFieldFilter(fieldFilter *IntelligentFieldValueFieldFilter) {
	i.FieldFilter = fieldFilter
	i.require(intelligentFieldValueSearchRequestFieldFieldFilter)
}

// SetEntityFilter sets the EntityFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetEntityFilter(entityFilter *IntelligentFieldValueEntityFilter) {
	i.EntityFilter = entityFilter
	i.require(intelligentFieldValueSearchRequestFieldEntityFilter)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetCreatedAfter(createdAfter *time.Time) {
	i.CreatedAfter = createdAfter
	i.require(intelligentFieldValueSearchRequestFieldCreatedAfter)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetCreatedBefore(createdBefore *time.Time) {
	i.CreatedBefore = createdBefore
	i.require(intelligentFieldValueSearchRequestFieldCreatedBefore)
}

// SetIncludeUnknownValues sets the IncludeUnknownValues field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetIncludeUnknownValues(includeUnknownValues *bool) {
	i.IncludeUnknownValues = includeUnknownValues
	i.require(intelligentFieldValueSearchRequestFieldIncludeUnknownValues)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetSort(sort *IntelligentFieldValueSortField) {
	i.Sort = sort
	i.require(intelligentFieldValueSearchRequestFieldSort)
}

// SetVariantID sets the VariantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchRequest) SetVariantID(variantID *EntityIDWithoutAgent) {
	i.VariantID = variantID
	i.require(intelligentFieldValueSearchRequestFieldVariantID)
}

func (i *IntelligentFieldValueSearchRequest) UnmarshalJSON(data []byte) error {
	type embed IntelligentFieldValueSearchRequest
	var unmarshaler = struct {
		embed
		CreatedAfter  *internal.DateTime `json:"createdAfter,omitempty"`
		CreatedBefore *internal.DateTime `json:"createdBefore,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IntelligentFieldValueSearchRequest(unmarshaler.embed)
	i.CreatedAfter = unmarshaler.CreatedAfter.TimePtr()
	i.CreatedBefore = unmarshaler.CreatedBefore.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldValueSearchRequest) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldValueSearchRequest
	var marshaler = struct {
		embed
		CreatedAfter  *internal.DateTime `json:"createdAfter,omitempty"`
		CreatedBefore *internal.DateTime `json:"createdBefore,omitempty"`
	}{
		embed:         embed(*i),
		CreatedAfter:  internal.NewOptionalDateTime(i.CreatedAfter),
		CreatedBefore: internal.NewOptionalDateTime(i.CreatedBefore),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldValueSearchRequest) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	intelligentFieldValueSearchResponseFieldNumber        = big.NewInt(1 << 0)
	intelligentFieldValueSearchResponseFieldSize          = big.NewInt(1 << 1)
	intelligentFieldValueSearchResponseFieldTotalElements = big.NewInt(1 << 2)
	intelligentFieldValueSearchResponseFieldTotalPages    = big.NewInt(1 << 3)
	intelligentFieldValueSearchResponseFieldValues        = big.NewInt(1 << 4)
)

type IntelligentFieldValueSearchResponse struct {
	// The page being returned, starts at 0
	Number int `json:"number" url:"number"`
	// The number of elements in this page
	Size int `json:"size" url:"size"`
	// The total number of elements in the collection
	TotalElements int64 `json:"totalElements" url:"totalElements"`
	// The total number of pages in the collection
	TotalPages int `json:"totalPages" url:"totalPages"`
	// Field values matching the search criteria, sorted by specified field
	Values []*IntelligentFieldValueResponse `json:"values" url:"values"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntelligentFieldValueSearchResponse) GetNumber() int {
	if i == nil {
		return 0
	}
	return i.Number
}

func (i *IntelligentFieldValueSearchResponse) GetSize() int {
	if i == nil {
		return 0
	}
	return i.Size
}

func (i *IntelligentFieldValueSearchResponse) GetTotalElements() int64 {
	if i == nil {
		return 0
	}
	return i.TotalElements
}

func (i *IntelligentFieldValueSearchResponse) GetTotalPages() int {
	if i == nil {
		return 0
	}
	return i.TotalPages
}

func (i *IntelligentFieldValueSearchResponse) GetValues() []*IntelligentFieldValueResponse {
	if i == nil {
		return nil
	}
	return i.Values
}

func (i *IntelligentFieldValueSearchResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntelligentFieldValueSearchResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchResponse) SetNumber(number int) {
	i.Number = number
	i.require(intelligentFieldValueSearchResponseFieldNumber)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchResponse) SetSize(size int) {
	i.Size = size
	i.require(intelligentFieldValueSearchResponseFieldSize)
}

// SetTotalElements sets the TotalElements field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchResponse) SetTotalElements(totalElements int64) {
	i.TotalElements = totalElements
	i.require(intelligentFieldValueSearchResponseFieldTotalElements)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchResponse) SetTotalPages(totalPages int) {
	i.TotalPages = totalPages
	i.require(intelligentFieldValueSearchResponseFieldTotalPages)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntelligentFieldValueSearchResponse) SetValues(values []*IntelligentFieldValueResponse) {
	i.Values = values
	i.require(intelligentFieldValueSearchResponseFieldValues)
}

func (i *IntelligentFieldValueSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IntelligentFieldValueSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntelligentFieldValueSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntelligentFieldValueSearchResponse) MarshalJSON() ([]byte, error) {
	type embed IntelligentFieldValueSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntelligentFieldValueSearchResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Fields that can be used to sort intelligent field value search results
type IntelligentFieldValueSortField string

const (
	IntelligentFieldValueSortFieldCreatedAt IntelligentFieldValueSortField = "CREATED_AT"
)

func NewIntelligentFieldValueSortFieldFromString(s string) (IntelligentFieldValueSortField, error) {
	switch s {
	case "CREATED_AT":
		return IntelligentFieldValueSortFieldCreatedAt, nil
	}
	var t IntelligentFieldValueSortField
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntelligentFieldValueSortField) Ptr() *IntelligentFieldValueSortField {
	return &i
}
