// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
)

var (
	baseOrganizationFieldName            = big.NewInt(1 << 0)
	baseOrganizationFieldDefaultLanguage = big.NewInt(1 << 1)
)

type BaseOrganization struct {
	// The name of the organization.
	Name string `json:"name" url:"name"`
	// The default language for the organization in ISO 639-1 code format.
	DefaultLanguage string `json:"defaultLanguage" url:"defaultLanguage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BaseOrganization) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BaseOrganization) GetDefaultLanguage() string {
	if b == nil {
		return ""
	}
	return b.DefaultLanguage
}

func (b *BaseOrganization) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BaseOrganization) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BaseOrganization) SetName(name string) {
	b.Name = name
	b.require(baseOrganizationFieldName)
}

// SetDefaultLanguage sets the DefaultLanguage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BaseOrganization) SetDefaultLanguage(defaultLanguage string) {
	b.DefaultLanguage = defaultLanguage
	b.require(baseOrganizationFieldDefaultLanguage)
}

func (b *BaseOrganization) UnmarshalJSON(data []byte) error {
	type unmarshaler BaseOrganization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BaseOrganization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BaseOrganization) MarshalJSON() ([]byte, error) {
	type embed BaseOrganization
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BaseOrganization) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	createOrganizationRequestFieldName            = big.NewInt(1 << 0)
	createOrganizationRequestFieldDefaultLanguage = big.NewInt(1 << 1)
)

type CreateOrganizationRequest struct {
	// The name of the organization.
	Name string `json:"name" url:"name"`
	// The default language for the organization in ISO 639-1 code format.
	DefaultLanguage string `json:"defaultLanguage" url:"defaultLanguage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateOrganizationRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOrganizationRequest) GetDefaultLanguage() string {
	if c == nil {
		return ""
	}
	return c.DefaultLanguage
}

func (c *CreateOrganizationRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateOrganizationRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateOrganizationRequest) SetName(name string) {
	c.Name = name
	c.require(createOrganizationRequestFieldName)
}

// SetDefaultLanguage sets the DefaultLanguage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateOrganizationRequest) SetDefaultLanguage(defaultLanguage string) {
	c.DefaultLanguage = defaultLanguage
	c.require(createOrganizationRequestFieldDefaultLanguage)
}

func (c *CreateOrganizationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateOrganizationRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateOrganizationRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateOrganizationRequest) MarshalJSON() ([]byte, error) {
	type embed CreateOrganizationRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateOrganizationRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	organizationFieldName            = big.NewInt(1 << 0)
	organizationFieldDefaultLanguage = big.NewInt(1 << 1)
	organizationFieldOrganizationID  = big.NewInt(1 << 2)
)

type Organization struct {
	// The name of the organization.
	Name string `json:"name" url:"name"`
	// The default language for the organization in ISO 639-1 code format.
	DefaultLanguage string `json:"defaultLanguage" url:"defaultLanguage"`
	// ID that uniquely identifies this organization
	OrganizationID *EntityIDBase `json:"organizationId" url:"organizationId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *Organization) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Organization) GetDefaultLanguage() string {
	if o == nil {
		return ""
	}
	return o.DefaultLanguage
}

func (o *Organization) GetOrganizationID() *EntityIDBase {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *Organization) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *Organization) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetName(name string) {
	o.Name = name
	o.require(organizationFieldName)
}

// SetDefaultLanguage sets the DefaultLanguage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetDefaultLanguage(defaultLanguage string) {
	o.DefaultLanguage = defaultLanguage
	o.require(organizationFieldDefaultLanguage)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *Organization) SetOrganizationID(organizationID *EntityIDBase) {
	o.OrganizationID = organizationID
	o.require(organizationFieldOrganizationID)
}

func (o *Organization) UnmarshalJSON(data []byte) error {
	type unmarshaler Organization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = Organization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *Organization) MarshalJSON() ([]byte, error) {
	type embed Organization
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *Organization) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

var (
	organizationPatchRequestFieldName            = big.NewInt(1 << 0)
	organizationPatchRequestFieldDefaultLanguage = big.NewInt(1 << 1)
)

type OrganizationPatchRequest struct {
	// The name of the organization.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The default language for the organization in ISO 639-1 code format.
	DefaultLanguage *string `json:"defaultLanguage,omitempty" url:"defaultLanguage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrganizationPatchRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OrganizationPatchRequest) GetDefaultLanguage() *string {
	if o == nil {
		return nil
	}
	return o.DefaultLanguage
}

func (o *OrganizationPatchRequest) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrganizationPatchRequest) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrganizationPatchRequest) SetName(name *string) {
	o.Name = name
	o.require(organizationPatchRequestFieldName)
}

// SetDefaultLanguage sets the DefaultLanguage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OrganizationPatchRequest) SetDefaultLanguage(defaultLanguage *string) {
	o.DefaultLanguage = defaultLanguage
	o.require(organizationPatchRequestFieldDefaultLanguage)
}

func (o *OrganizationPatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler OrganizationPatchRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrganizationPatchRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrganizationPatchRequest) MarshalJSON() ([]byte, error) {
	type embed OrganizationPatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OrganizationPatchRequest) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
