// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mavenagi/mavenagi-go/internal"
	big "math/big"
	time "time"
)

var (
	userDeleteRequestFieldAppId = big.NewInt(1 << 0)
)

type UserDeleteRequest struct {
	// The App ID of the app user to delete. If not provided the ID of the calling app will be used.
	AppId *string `json:"-" url:"appId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UserDeleteRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAppId sets the AppId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserDeleteRequest) SetAppId(appId *string) {
	u.AppId = appId
	u.require(userDeleteRequestFieldAppId)
}

var (
	userGetRequestFieldAppId = big.NewInt(1 << 0)
)

type UserGetRequest struct {
	// The App ID of the app user to get. If not provided the ID of the calling app will be used.
	AppId *string `json:"-" url:"appId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UserGetRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAppId sets the AppId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserGetRequest) SetAppId(appId *string) {
	u.AppId = appId
	u.require(userGetRequestFieldAppId)
}

var (
	agentUserFieldId          = big.NewInt(1 << 0)
	agentUserFieldCreatedAt   = big.NewInt(1 << 1)
	agentUserFieldUpdatedAt   = big.NewInt(1 << 2)
	agentUserFieldIdentifiers = big.NewInt(1 << 3)
	agentUserFieldDefaultName = big.NewInt(1 << 4)
	agentUserFieldUsers       = big.NewInt(1 << 5)
)

type AgentUser struct {
	// The ID of the agent user.
	Id string `json:"id" url:"id"`
	// The date and time the agent user was created
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// The date and time the agent user was last updated
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	// All identifiers for the agent user. This is a merged set of identifiers from the app created users.
	Identifiers []*AppUserIdentifier `json:"identifiers" url:"identifiers"`
	// A name for the agent user, if one can be determined.
	// The value is derived from the user data provided by individual apps - specifically data fields keyed by `name`, `first_name` or `firstName`.
	DefaultName *string `json:"defaultName,omitempty" url:"defaultName,omitempty"`
	// App created users that are associated with this agent user.
	// If two apps create users with the same identifying properties, they will be merged into a single agent user.
	Users []*AppUserSummary `json:"users" url:"users"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentUser) GetId() string {
	if a == nil {
		return ""
	}
	return a.Id
}

func (a *AgentUser) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AgentUser) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}

func (a *AgentUser) GetIdentifiers() []*AppUserIdentifier {
	if a == nil {
		return nil
	}
	return a.Identifiers
}

func (a *AgentUser) GetDefaultName() *string {
	if a == nil {
		return nil
	}
	return a.DefaultName
}

func (a *AgentUser) GetUsers() []*AppUserSummary {
	if a == nil {
		return nil
	}
	return a.Users
}

func (a *AgentUser) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentUser) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetId(id string) {
	a.Id = id
	a.require(agentUserFieldId)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetCreatedAt(createdAt time.Time) {
	a.CreatedAt = createdAt
	a.require(agentUserFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetUpdatedAt(updatedAt time.Time) {
	a.UpdatedAt = updatedAt
	a.require(agentUserFieldUpdatedAt)
}

// SetIdentifiers sets the Identifiers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetIdentifiers(identifiers []*AppUserIdentifier) {
	a.Identifiers = identifiers
	a.require(agentUserFieldIdentifiers)
}

// SetDefaultName sets the DefaultName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetDefaultName(defaultName *string) {
	a.DefaultName = defaultName
	a.require(agentUserFieldDefaultName)
}

// SetUsers sets the Users field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUser) SetUsers(users []*AppUserSummary) {
	a.Users = users
	a.require(agentUserFieldUsers)
}

func (a *AgentUser) UnmarshalJSON(data []byte) error {
	type embed AgentUser
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AgentUser(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.Time()
	a.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentUser) MarshalJSON() ([]byte, error) {
	type embed AgentUser
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*a),
		CreatedAt: internal.NewDateTime(a.CreatedAt),
		UpdatedAt: internal.NewDateTime(a.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentUser) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentUserField string

const (
	AgentUserFieldCreatedAt AgentUserField = "CreatedAt"
	AgentUserFieldUpdatedAt AgentUserField = "UpdatedAt"
)

func NewAgentUserFieldFromString(s string) (AgentUserField, error) {
	switch s {
	case "CreatedAt":
		return AgentUserFieldCreatedAt, nil
	case "UpdatedAt":
		return AgentUserFieldUpdatedAt, nil
	}
	var t AgentUserField
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentUserField) Ptr() *AgentUserField {
	return &a
}

var (
	agentUserFilterFieldSearch      = big.NewInt(1 << 0)
	agentUserFilterFieldIdentifiers = big.NewInt(1 << 1)
	agentUserFilterFieldDisplayName = big.NewInt(1 << 2)
	agentUserFilterFieldIsAnonymous = big.NewInt(1 << 3)
)

type AgentUserFilter struct {
	// Full-text search query for matching agent users by content.
	// When you search with this parameter, you're performing a full-text search across the user identifiers.
	Search *string `json:"search,omitempty" url:"search,omitempty"`
	// Filter by identifiers
	Identifiers []string `json:"identifiers,omitempty" url:"identifiers,omitempty"`
	// Full-text search query for matching agent users by display name.
	// When you search with this parameter, you're performing a full-text search across the user display names.
	DisplayName *string `json:"displayName,omitempty" url:"displayName,omitempty"`
	// Filter by anonymous users. When true, only anonymous users are returned.
	// When false, only non-anonymous users are returned. An anonymous user is one without any identifiers or name data.
	IsAnonymous *bool `json:"isAnonymous,omitempty" url:"isAnonymous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentUserFilter) GetSearch() *string {
	if a == nil {
		return nil
	}
	return a.Search
}

func (a *AgentUserFilter) GetIdentifiers() []string {
	if a == nil {
		return nil
	}
	return a.Identifiers
}

func (a *AgentUserFilter) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AgentUserFilter) GetIsAnonymous() *bool {
	if a == nil {
		return nil
	}
	return a.IsAnonymous
}

func (a *AgentUserFilter) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentUserFilter) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserFilter) SetSearch(search *string) {
	a.Search = search
	a.require(agentUserFilterFieldSearch)
}

// SetIdentifiers sets the Identifiers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserFilter) SetIdentifiers(identifiers []string) {
	a.Identifiers = identifiers
	a.require(agentUserFilterFieldIdentifiers)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserFilter) SetDisplayName(displayName *string) {
	a.DisplayName = displayName
	a.require(agentUserFilterFieldDisplayName)
}

// SetIsAnonymous sets the IsAnonymous field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserFilter) SetIsAnonymous(isAnonymous *bool) {
	a.IsAnonymous = isAnonymous
	a.require(agentUserFilterFieldIsAnonymous)
}

func (a *AgentUserFilter) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentUserFilter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentUserFilter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentUserFilter) MarshalJSON() ([]byte, error) {
	type embed AgentUserFilter
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentUserFilter) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentUserSearchRequestFieldPage     = big.NewInt(1 << 0)
	agentUserSearchRequestFieldSize     = big.NewInt(1 << 1)
	agentUserSearchRequestFieldSortDesc = big.NewInt(1 << 2)
	agentUserSearchRequestFieldSort     = big.NewInt(1 << 3)
	agentUserSearchRequestFieldFilter   = big.NewInt(1 << 4)
)

type AgentUserSearchRequest struct {
	// Page number to return, defaults to 0
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// The size of the page to return, defaults to 20
	Size *int `json:"size,omitempty" url:"size,omitempty"`
	// Whether to sort descending, defaults to true
	SortDesc *bool            `json:"sortDesc,omitempty" url:"sortDesc,omitempty"`
	Sort     *AgentUserField  `json:"sort,omitempty" url:"sort,omitempty"`
	Filter   *AgentUserFilter `json:"filter,omitempty" url:"filter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentUserSearchRequest) GetPage() *int {
	if a == nil {
		return nil
	}
	return a.Page
}

func (a *AgentUserSearchRequest) GetSize() *int {
	if a == nil {
		return nil
	}
	return a.Size
}

func (a *AgentUserSearchRequest) GetSortDesc() *bool {
	if a == nil {
		return nil
	}
	return a.SortDesc
}

func (a *AgentUserSearchRequest) GetSort() *AgentUserField {
	if a == nil {
		return nil
	}
	return a.Sort
}

func (a *AgentUserSearchRequest) GetFilter() *AgentUserFilter {
	if a == nil {
		return nil
	}
	return a.Filter
}

func (a *AgentUserSearchRequest) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentUserSearchRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchRequest) SetPage(page *int) {
	a.Page = page
	a.require(agentUserSearchRequestFieldPage)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchRequest) SetSize(size *int) {
	a.Size = size
	a.require(agentUserSearchRequestFieldSize)
}

// SetSortDesc sets the SortDesc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchRequest) SetSortDesc(sortDesc *bool) {
	a.SortDesc = sortDesc
	a.require(agentUserSearchRequestFieldSortDesc)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchRequest) SetSort(sort *AgentUserField) {
	a.Sort = sort
	a.require(agentUserSearchRequestFieldSort)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchRequest) SetFilter(filter *AgentUserFilter) {
	a.Filter = filter
	a.require(agentUserSearchRequestFieldFilter)
}

func (a *AgentUserSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentUserSearchRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentUserSearchRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentUserSearchRequest) MarshalJSON() ([]byte, error) {
	type embed AgentUserSearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentUserSearchRequest) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentUserSearchResponseFieldNumber        = big.NewInt(1 << 0)
	agentUserSearchResponseFieldSize          = big.NewInt(1 << 1)
	agentUserSearchResponseFieldTotalElements = big.NewInt(1 << 2)
	agentUserSearchResponseFieldTotalPages    = big.NewInt(1 << 3)
	agentUserSearchResponseFieldAgentUsers    = big.NewInt(1 << 4)
)

type AgentUserSearchResponse struct {
	// The page being returned, starts at 0
	Number int `json:"number" url:"number"`
	// The number of elements in this page
	Size int `json:"size" url:"size"`
	// The total number of elements in the collection
	TotalElements int64 `json:"totalElements" url:"totalElements"`
	// The total number of pages in the collection
	TotalPages int `json:"totalPages" url:"totalPages"`
	// The agent users that match the search criteria
	AgentUsers []*AgentUser `json:"agentUsers" url:"agentUsers"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentUserSearchResponse) GetNumber() int {
	if a == nil {
		return 0
	}
	return a.Number
}

func (a *AgentUserSearchResponse) GetSize() int {
	if a == nil {
		return 0
	}
	return a.Size
}

func (a *AgentUserSearchResponse) GetTotalElements() int64 {
	if a == nil {
		return 0
	}
	return a.TotalElements
}

func (a *AgentUserSearchResponse) GetTotalPages() int {
	if a == nil {
		return 0
	}
	return a.TotalPages
}

func (a *AgentUserSearchResponse) GetAgentUsers() []*AgentUser {
	if a == nil {
		return nil
	}
	return a.AgentUsers
}

func (a *AgentUserSearchResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentUserSearchResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchResponse) SetNumber(number int) {
	a.Number = number
	a.require(agentUserSearchResponseFieldNumber)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchResponse) SetSize(size int) {
	a.Size = size
	a.require(agentUserSearchResponseFieldSize)
}

// SetTotalElements sets the TotalElements field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchResponse) SetTotalElements(totalElements int64) {
	a.TotalElements = totalElements
	a.require(agentUserSearchResponseFieldTotalElements)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchResponse) SetTotalPages(totalPages int) {
	a.TotalPages = totalPages
	a.require(agentUserSearchResponseFieldTotalPages)
}

// SetAgentUsers sets the AgentUsers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentUserSearchResponse) SetAgentUsers(agentUsers []*AgentUser) {
	a.AgentUsers = agentUsers
	a.require(agentUserSearchResponseFieldAgentUsers)
}

func (a *AgentUserSearchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentUserSearchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentUserSearchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentUserSearchResponse) MarshalJSON() ([]byte, error) {
	type embed AgentUserSearchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentUserSearchResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	appUserSummaryFieldUserId      = big.NewInt(1 << 0)
	appUserSummaryFieldIdentifiers = big.NewInt(1 << 1)
	appUserSummaryFieldVisibleData = big.NewInt(1 << 2)
)

type AppUserSummary struct {
	// App provided user ID.
	UserId *EntityId `json:"userId" url:"userId"`
	// App provided identifiers for the user.
	Identifiers []*AppUserIdentifier `json:"identifiers" url:"identifiers"`
	// App provided data masked according to the data's visibility type. `HIDDEN` or `PARTIALLY_VISIBLE` data values will be not be fully returned.
	VisibleData map[string]string `json:"visibleData" url:"visibleData"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AppUserSummary) GetUserId() *EntityId {
	if a == nil {
		return nil
	}
	return a.UserId
}

func (a *AppUserSummary) GetIdentifiers() []*AppUserIdentifier {
	if a == nil {
		return nil
	}
	return a.Identifiers
}

func (a *AppUserSummary) GetVisibleData() map[string]string {
	if a == nil {
		return nil
	}
	return a.VisibleData
}

func (a *AppUserSummary) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AppUserSummary) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AppUserSummary) SetUserId(userId *EntityId) {
	a.UserId = userId
	a.require(appUserSummaryFieldUserId)
}

// SetIdentifiers sets the Identifiers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AppUserSummary) SetIdentifiers(identifiers []*AppUserIdentifier) {
	a.Identifiers = identifiers
	a.require(appUserSummaryFieldIdentifiers)
}

// SetVisibleData sets the VisibleData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AppUserSummary) SetVisibleData(visibleData map[string]string) {
	a.VisibleData = visibleData
	a.require(appUserSummaryFieldVisibleData)
}

func (a *AppUserSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler AppUserSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AppUserSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AppUserSummary) MarshalJSON() ([]byte, error) {
	type embed AppUserSummary
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AppUserSummary) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
