// Code generated by Fern. DO NOT EDIT.

package appsettings

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppId == "" {
		options.AppId = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Search for app settings which have the `$index` key set to the provided value.
//
// You can set the `$index` key using the Update app settings API.
//
// <Warning>This API currently requires an organization ID and agent ID for any agent which is installed on the app. This requirement will be removed in a future update.</Warning>
func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.SearchAppSettingsRequest,
	opts ...option.RequestOption,
) (*mavenagigo.SearchAppSettingsResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get app settings set during installation
func (c *Client) Get(
	ctx context.Context,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update app settings. Performs a merge of the provided settings with the existing app settings.
//
// - If a new key is provided, it will be added to the app settings.
// - If an existing key is provided, it will be updated.
// - No keys will be removed.
//
// Note that if an array value is provided it will fully replace an existing value as arrays cannot be merged.
func (c *Client) Update(
	ctx context.Context,
	request map[string]any,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
