// Code generated by Fern. DO NOT EDIT.

package charters

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Create a new charter or update an existing one. Charters are governing
// documents that combine a precondition (when the charter applies), a manual
// (what the LLM should do), and the knowledge bases and actions the charter
// makes available.
//
// All charters in an agent form a tree (forest / multi-roots). When a
// charter is matched on a round, all its ancestor charters will be
// incorporated. Non-leaf charters are referred to as a charter group.
//
// Charters may specify a 0-indexed custom `userRank` that indicates
// preferences among its siblings. The rank is currently only meaningful
// for leaf charters as we enforce mutual exclusion among the leafs and
// pick only the highest ranked (lowest numerical value) leaf to include in
// the round. userRank may have gaps.
func (c *Client) CreateOrUpdate(
	ctx context.Context,
	request *mavenagigo.CharterRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterResponse, error) {
	response, err := c.WithRawResponse.CreateOrUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a charter by its reference ID.
func (c *Client) Get(
	ctx context.Context,
	// The reference ID of the charter to get. All other entity ID fields are inferred from the request.
	charterReferenceID string,
	request *mavenagigo.CharterGetRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		charterReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update mutable fields on a charter. Only provided fields are modified.
//
// To move a charter within the tree, set `parentCharterId`.
// To promote to root level, set `parentCharterId` explicitly to null.
//
// **Status behavior**:
//   - Setting `status` to `INACTIVE` applies only to the targeted charter;
//     it does not cascade to descendants. However, its descendants will no
//     longer be incorporated at runtime.
//   - Setting `status` to `ACTIVE` applies only to the targeted charter.
//     The caller is responsible for ensuring ancestor charters are also `ACTIVE`
//     if the full subtree should be reachable at runtime.
//
// **userRank conflict resolution**: When `userRank` is set to a value already held by a
// sibling, siblings at that rank and above are shifted up by 1 (like linked list semantics).
// The caller does not need to manage uniqueness explicitly.
func (c *Client) Patch(
	ctx context.Context,
	// The reference ID of the charter to patch.
	charterReferenceID string,
	request *mavenagigo.CharterPatchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterResponse, error) {
	response, err := c.WithRawResponse.Patch(
		ctx,
		charterReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a charter and all of its descendants recursively.
//
// The charter must be set to `INACTIVE` before it can be deleted. This prevents accidental
// deletion of active charters. Descendant charters may be in any status — they will be
// soft-deleted regardless.
//
// Deleted charters are excluded from list results but can be retrieved by ID for archival purposes.
//
// Deleted charters cannot be modified.
func (c *Client) Delete(
	ctx context.Context,
	// The reference ID of the charter to delete.
	charterReferenceID string,
	request *mavenagigo.CharterDeleteRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		charterReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Search for charters matching the provided filters. Supports filtering by
// referenced action IDs and knowledge base IDs to find charters that make
// specific context items available.
//
// Returns both ACTIVE and INACTIVE charters (DELETED charters are excluded).
//
// Results are ordered by the `sort` field (defaults to CreatedAt). Use `sortDesc`
// to control direction (defaults to descending). An empty filter list is
// equivalent to omitting the field (no filter applied).
func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.CharterSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Return a flat list containing the specified charter and all of its ancestors
// up to the root. Useful for rendering tree context around search results.
//
// Each entry is a full charter, so an ancestor's references and precondition are
// readable without a follow-up request per level.
//
// The list is always finite: charter hierarchies are acyclic, so a charter is never its own
// ancestor and the walk to the root terminates.
//
// Returns 404 if the charter does not exist or is deleted.
func (c *Client) GetAncestors(
	ctx context.Context,
	// The reference ID of the charter. All other entity ID fields are inferred from the request.
	charterReferenceID string,
	request *mavenagigo.CharterGetAncestorsRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterAncestorsResponse, error) {
	response, err := c.WithRawResponse.GetAncestors(
		ctx,
		charterReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Batch fetch direct children of the specified parent charters. Returns one
// group per requested parent in the same order as parentIds, with grandchild
// IDs populated on each child for expandability signals.
//
// Pass an empty parentIds list to fetch all root-level charters for the agent.
// Intended to be used for easy BFS traversal, though calling with parents
// at mixed levels are allowed. Roots and specific parents cannot be mixed
// in one request.
//
// DELETED charters are never returned.
func (c *Client) ListChildren(
	ctx context.Context,
	request *mavenagigo.CharterListChildrenRequest,
	opts ...option.RequestOption,
) (*mavenagigo.CharterListChildrenResponse, error) {
	response, err := c.WithRawResponse.ListChildren(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
