// Code generated by Fern. DO NOT EDIT.

package charters

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) CreateOrUpdate(
	ctx context.Context,
	request *mavenagigo.CharterRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := baseURL + "/v1/charters"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Get(
	ctx context.Context,
	// The reference ID of the charter to get. All other entity ID fields are inferred from the request.
	charterReferenceID string,
	request *mavenagigo.CharterGetRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/charters/%v",
		charterReferenceID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Patch(
	ctx context.Context,
	// The reference ID of the charter to patch.
	charterReferenceID string,
	request *mavenagigo.CharterPatchRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/charters/%v",
		charterReferenceID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/merge-patch+json")
	var response *mavenagigo.CharterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	// The reference ID of the charter to delete.
	charterReferenceID string,
	request *mavenagigo.CharterDeleteRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/charters/%v",
		charterReferenceID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Search(
	ctx context.Context,
	request *mavenagigo.CharterSearchRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterSearchResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := baseURL + "/v1/charters/search"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterSearchResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterSearchResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetAncestors(
	ctx context.Context,
	// The reference ID of the charter. All other entity ID fields are inferred from the request.
	charterReferenceID string,
	request *mavenagigo.CharterGetAncestorsRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterAncestorsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v1/charters/%v/ancestors",
		charterReferenceID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterAncestorsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterAncestorsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListChildren(
	ctx context.Context,
	request *mavenagigo.CharterListChildrenRequest,
	opts ...option.RequestOption,
) (*core.Response[*mavenagigo.CharterListChildrenResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://www.mavenagi-apis.com",
	)
	endpointURL := baseURL + "/v1/charters/list-children"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *mavenagigo.CharterListChildrenResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(mavenagigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*mavenagigo.CharterListChildrenResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
