// Code generated by Fern. DO NOT EDIT.

package analytics_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	client "github.com/mavenagi/mavenagi-go/client"
	option "github.com/mavenagi/mavenagi-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAnalyticsGetConversationTableWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationTableRequest{
		ConversationFilter: &mavenagigo.ConversationFilter{
			Languages: []string{
				"en",
				"es",
			},
		},
		TimeGrouping: mavenagigo.TimeIntervalDay.Ptr(),
		FieldGroupings: []*mavenagigo.ConversationGroupBy{
			&mavenagigo.ConversationGroupBy{
				Field: mavenagigo.ConversationFieldCategory,
			},
		},
		ColumnDefinitions: []*mavenagigo.ConversationColumnDefinition{
			&mavenagigo.ConversationColumnDefinition{
				Header: "count",
				Metric: &mavenagigo.ConversationMetric{
					Count: &mavenagigo.ConversationCount{},
				},
			},
			&mavenagigo.ConversationColumnDefinition{
				Header: "avg_first_response_time",
				Metric: &mavenagigo.ConversationMetric{
					Average: &mavenagigo.ConversationAverage{
						TargetField: mavenagigo.NumericConversationFieldFirstResponseTime,
					},
				},
			},
			&mavenagigo.ConversationColumnDefinition{
				Header: "percentile_handle_time",
				Metric: &mavenagigo.ConversationMetric{
					Percentile: &mavenagigo.ConversationPercentile{
						TargetField: mavenagigo.NumericConversationFieldHandleTime,
						Percentile:  25,
					},
				},
			},
		},
	}
	_, invocationErr := client.Analytics.GetConversationTable(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tables/conversations", nil, 1)
}

func TestAnalyticsGetConversationChartWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationChartRequest{
		PieChart: &mavenagigo.ConversationPieChartRequest{
			ConversationFilter: &mavenagigo.ConversationFilter{
				Languages: []string{
					"en",
					"es",
				},
			},
			GroupBy: &mavenagigo.ConversationGroupBy{
				Field: mavenagigo.ConversationFieldCategory,
			},
			Metric: &mavenagigo.ConversationMetric{
				Count: &mavenagigo.ConversationCount{},
			},
		},
	}
	_, invocationErr := client.Analytics.GetConversationChart(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/charts/conversations", nil, 1)
}

func TestAnalyticsExportConversationTableWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationTableRequest{
		FieldGroupings: []*mavenagigo.ConversationGroupBy{
			&mavenagigo.ConversationGroupBy{
				Field: mavenagigo.ConversationFieldCategory,
			},
			&mavenagigo.ConversationGroupBy{
				Field: mavenagigo.ConversationFieldCategory,
			},
		},
		ColumnDefinitions: []*mavenagigo.ConversationColumnDefinition{
			&mavenagigo.ConversationColumnDefinition{
				Metric: &mavenagigo.ConversationMetric{
					Count: &mavenagigo.ConversationCount{},
				},
				Header: "header",
			},
			&mavenagigo.ConversationColumnDefinition{
				Metric: &mavenagigo.ConversationMetric{
					Count: &mavenagigo.ConversationCount{},
				},
				Header: "header",
			},
		},
	}
	_, invocationErr := client.Analytics.ExportConversationTable(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tables/conversations/export", nil, 1)
}

func TestAnalyticsGetFeedbackTableWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.FeedbackTableRequest{
		FeedbackFilter: &mavenagigo.FeedbackFilter{
			Types: []mavenagigo.FeedbackType{
				mavenagigo.FeedbackTypeThumbsUp,
				mavenagigo.FeedbackTypeInsert,
			},
		},
		FieldGroupings: []*mavenagigo.FeedbackGroupBy{
			&mavenagigo.FeedbackGroupBy{
				Field: mavenagigo.FeedbackFieldCreatedBy,
			},
		},
		ColumnDefinitions: []*mavenagigo.FeedbackColumnDefinition{
			&mavenagigo.FeedbackColumnDefinition{
				Header: "feedback_count",
				Metric: &mavenagigo.FeedbackMetric{
					Count: &mavenagigo.FeedbackCount{},
				},
			},
		},
	}
	_, invocationErr := client.Analytics.GetFeedbackTable(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tables/feedback", nil, 1)
}

func TestAnalyticsGetAgentUserTableWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.AgentUserTableRequest{
		AgentUserFilter: &mavenagigo.AgentUserFilter{
			Search: mavenagigo.String(
				"john",
			),
		},
		ColumnDefinitions: []*mavenagigo.AgentUserColumnDefinition{
			&mavenagigo.AgentUserColumnDefinition{
				Header: "user_count",
				Metric: &mavenagigo.AgentUserMetric{
					Count: &mavenagigo.AgentUserCount{},
				},
			},
		},
	}
	_, invocationErr := client.Analytics.GetAgentUserTable(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tables/agent-users", nil, 1)
}

func TestAnalyticsGetEventTableWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.EventTableRequest{
		EventFilter: &mavenagigo.EventFilter{
			EventTypes: []mavenagigo.EventType{
				mavenagigo.EventTypeUser,
			},
		},
		FieldGroupings: []*mavenagigo.EventGroupBy{
			&mavenagigo.EventGroupBy{
				Field: mavenagigo.EventFieldEventName,
			},
		},
		ColumnDefinitions: []*mavenagigo.EventColumnDefinition{
			&mavenagigo.EventColumnDefinition{
				Header: "event_count",
				Metric: &mavenagigo.EventMetric{
					Count: &mavenagigo.EventCount{},
				},
			},
		},
	}
	_, invocationErr := client.Analytics.GetEventTable(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tables/events", nil, 1)
}

func TestAnalyticsGetEventChartWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.EventChartRequest{
		PieChart: &mavenagigo.EventPieChartRequest{
			EventFilter: &mavenagigo.EventFilter{
				EventTypes: []mavenagigo.EventType{
					mavenagigo.EventTypeUser,
				},
			},
			GroupBy: &mavenagigo.EventGroupBy{
				Field: mavenagigo.EventFieldEventName,
			},
			Metric: &mavenagigo.EventMetric{
				Count: &mavenagigo.EventCount{},
			},
		},
	}
	_, invocationErr := client.Analytics.GetEventChart(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/charts/events", nil, 1)
}
