// Code generated by Fern. DO NOT EDIT.

package intelligentfields

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Create a new intelligent field, or replace it if one already exists with the same
// `fieldId.referenceId`. Intelligent fields hold LLM-generated values computed for
// entities such as conversations.
//
// New fields are created with `status: INACTIVE` and are not evaluated until activated
// with the patch endpoint. `definition` is limited to 5,000 characters.
func (c *Client) CreateOrUpdate(
	ctx context.Context,
	request *mavenagigo.IntelligentFieldRequest,
	opts ...option.RequestOption,
) (*mavenagigo.IntelligentFieldResponse, error) {
	response, err := c.WithRawResponse.CreateOrUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get an intelligent field by its supplied ID
func (c *Client) Get(
	ctx context.Context,
	// The reference ID of the intelligent field to get. All other entity ID fields are inferred from the request.
	fieldReferenceID string,
	request *mavenagigo.IntelligentFieldGetRequest,
	opts ...option.RequestOption,
) (*mavenagigo.IntelligentFieldDetailResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		fieldReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the mutable properties of an intelligent field. Only the properties present in
// the request body are changed.
//
// This is also how a field is activated and deactivated: set `status` to `ACTIVE` to
// start evaluating it, or `INACTIVE` to stop. `name`, `entityType`, and `validationType`
// cannot be changed after creation.
func (c *Client) Patch(
	ctx context.Context,
	// The reference ID of the intelligent field to patch.
	fieldReferenceID string,
	request *mavenagigo.IntelligentFieldPatchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.IntelligentFieldResponse, error) {
	response, err := c.WithRawResponse.Patch(
		ctx,
		fieldReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Soft delete an intelligent field. Only INACTIVE fields can be deleted.
//
// Deleted fields are excluded from search results but can still be retrieved by ID.
// Creating a new field with the same referenceId as a deleted field will overwrite
// the deleted field and restore it to INACTIVE status.
//
// Deleted fields cannot be modified.
func (c *Client) Delete(
	ctx context.Context,
	// The reference ID of the intelligent field to delete.
	fieldReferenceID string,
	request *mavenagigo.IntelligentFieldDeleteRequest,
	opts ...option.RequestOption,
) (*mavenagigo.IntelligentFieldResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		fieldReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Search the values that have been computed for intelligent fields, across entities.
// Supports filtering by properties of the field, by target entity, and by when the
// value was computed.
//
// Values only exist for fields that were ACTIVE when the entity was evaluated, so a
// newly activated field returns nothing until evaluation has run.
func (c *Client) SearchValues(
	ctx context.Context,
	request *mavenagigo.IntelligentFieldValueSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.IntelligentFieldValueSearchResponse, error) {
	response, err := c.WithRawResponse.SearchValues(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
