// Code generated by Fern. DO NOT EDIT.

package core

import (
	base64 "encoding/base64"
	fmt "fmt"
	http "net/http"
	url "net/url"
)

// RequestOption adapts the behavior of the client or an individual request.
type RequestOption interface {
	applyRequestOptions(*RequestOptions)
}

// RequestOptions defines all of the possible request options.
//
// This type is primarily used by the generated code and is not meant
// to be used directly; use the option package instead.
type RequestOptions struct {
	BaseURL         string
	HTTPClient      HTTPClient
	HTTPHeader      http.Header
	BodyProperties  map[string]interface{}
	QueryParameters url.Values
	MaxAttempts     uint
	AppID           string
	AppSecret       string
	OrganizationID  string
	AgentID         string
}

// NewRequestOptions returns a new *RequestOptions value.
//
// This function is primarily used by the generated code and is not meant
// to be used directly; use RequestOption instead.
func NewRequestOptions(opts ...RequestOption) *RequestOptions {
	options := &RequestOptions{
		HTTPHeader:      make(http.Header),
		BodyProperties:  make(map[string]interface{}),
		QueryParameters: make(url.Values),
	}
	for _, opt := range opts {
		opt.applyRequestOptions(options)
	}
	return options
}

// ToHeader maps the configured request options into a http.Header used
// for the request(s).
func (r *RequestOptions) ToHeader() http.Header {
	header := r.cloneHeader()
	if r.AppID != "" && r.AppSecret != "" {
		header.Set("Authorization", "Basic "+base64.StdEncoding.EncodeToString([]byte(r.AppID+": "+r.AppSecret)))
	}
	header.Set("X-Organization-Id", fmt.Sprintf("%v", r.OrganizationID))
	header.Set("X-Agent-Id", fmt.Sprintf("%v", r.AgentID))
	return header
}

func (r *RequestOptions) cloneHeader() http.Header {
	headers := r.HTTPHeader.Clone()
	headers.Set("X-Fern-Language", "Go")
	headers.Set("X-Fern-SDK-Name", "github.com/mavenagi/mavenagi-go")
	headers.Set("X-Fern-SDK-Version", "v1.2.13")
	headers.Set("User-Agent", "github.com/mavenagi/mavenagi-go/1.2.13")
	return headers
}

// BaseURLOption implements the RequestOption interface.
type BaseURLOption struct {
	BaseURL string
}

func (b *BaseURLOption) applyRequestOptions(opts *RequestOptions) {
	opts.BaseURL = b.BaseURL
}

// HTTPClientOption implements the RequestOption interface.
type HTTPClientOption struct {
	HTTPClient HTTPClient
}

func (h *HTTPClientOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPClient = h.HTTPClient
}

// HTTPHeaderOption implements the RequestOption interface.
type HTTPHeaderOption struct {
	HTTPHeader http.Header
}

func (h *HTTPHeaderOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPHeader = h.HTTPHeader
}

// BodyPropertiesOption implements the RequestOption interface.
type BodyPropertiesOption struct {
	BodyProperties map[string]interface{}
}

func (b *BodyPropertiesOption) applyRequestOptions(opts *RequestOptions) {
	opts.BodyProperties = b.BodyProperties
}

// QueryParametersOption implements the RequestOption interface.
type QueryParametersOption struct {
	QueryParameters url.Values
}

func (q *QueryParametersOption) applyRequestOptions(opts *RequestOptions) {
	opts.QueryParameters = q.QueryParameters
}

// MaxAttemptsOption implements the RequestOption interface.
type MaxAttemptsOption struct {
	MaxAttempts uint
}

func (m *MaxAttemptsOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxAttempts = m.MaxAttempts
}

// BasicAuthOption implements the RequestOption interface.
type BasicAuthOption struct {
	AppID     string
	AppSecret string
}

func (b *BasicAuthOption) applyRequestOptions(opts *RequestOptions) {
	opts.AppID = b.AppID
	opts.AppSecret = b.AppSecret
}

// OrganizationIDOption implements the RequestOption interface.
type OrganizationIDOption struct {
	OrganizationID string
}

func (o *OrganizationIDOption) applyRequestOptions(opts *RequestOptions) {
	opts.OrganizationID = o.OrganizationID
}

// AgentIDOption implements the RequestOption interface.
type AgentIDOption struct {
	AgentID string
}

func (a *AgentIDOption) applyRequestOptions(opts *RequestOptions) {
	opts.AgentID = a.AgentID
}
