// Code generated by Fern. DO NOT EDIT.

package charters_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	client "github.com/mavenagi/mavenagi-go/client"
	option "github.com/mavenagi/mavenagi-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestChartersCreateOrUpdateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterRequest{
		CharterID: &mavenagigo.EntityIDBase{
			ReferenceID: "cancellation-flow",
		},
		Name: "Cancellation Flow",
		Manual: mavenagigo.String(
			"Guide the user through the cancellation process with empathy. Always confirm their intent before proceeding.",
		),
		Precondition: &mavenagigo.Precondition{},
		Status:       mavenagigo.CharterStatusActive,
		Type:         mavenagigo.CharterTypeStandard.Ptr(),
		References: &mavenagigo.CharterReferences{
			KnowledgeBases: []*mavenagigo.CharterKnowledgeBaseReference{},
			ActionIDs:      []*mavenagigo.EntityID{},
		},
	}
	_, invocationErr := client.Charters.CreateOrUpdate(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PUT", "/v1/charters", nil, 1)
}

func TestChartersGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterGetRequest{}
	_, invocationErr := client.Charters.Get(
		context.TODO(),
		"cancellation-flow",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v1/charters/cancellation-flow", nil, 1)
}

func TestChartersPatchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterPatchRequest{
		Precondition: &mavenagigo.Precondition{},
		Status:       mavenagigo.CharterStatusActive.Ptr(),
	}
	_, invocationErr := client.Charters.Patch(
		context.TODO(),
		"cancellation-flow",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v1/charters/cancellation-flow", nil, 1)
}

func TestChartersDeleteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterDeleteRequest{}
	_, invocationErr := client.Charters.Delete(
		context.TODO(),
		"cancellation-flow",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/v1/charters/cancellation-flow", nil, 1)
}

func TestChartersSearchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterSearchRequest{
		Page: mavenagigo.Int(
			0,
		),
		Size: mavenagigo.Int(
			20,
		),
	}
	_, invocationErr := client.Charters.Search(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/charters/search", nil, 1)
}

func TestChartersGetAncestorsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterGetAncestorsRequest{}
	_, invocationErr := client.Charters.GetAncestors(
		context.TODO(),
		"cancellation-step-1",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v1/charters/cancellation-step-1/ancestors", nil, 1)
}

func TestChartersListChildrenWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.CharterListChildrenRequest{
		ParentIDs: []*mavenagigo.EntityID{},
	}
	_, invocationErr := client.Charters.ListChildren(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/charters/list-children", nil, 1)
}
