// Code generated by Fern. DO NOT EDIT.

package translations

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Translate text from one language to another
func (c *Client) Translate(
	ctx context.Context,
	request *mavenagigo.TranslationRequest,
	opts ...option.RequestOption,
) (*mavenagigo.TranslationResponse, error) {
	response, err := c.WithRawResponse.Translate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
