// Code generated by Fern. DO NOT EDIT.

package segments

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.SegmentsSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.SegmentsSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update a segment or create it if it doesn't exist.
func (c *Client) CreateOrUpdate(
	ctx context.Context,
	request *mavenagigo.SegmentRequest,
	opts ...option.RequestOption,
) (*mavenagigo.SegmentResponse, error) {
	response, err := c.WithRawResponse.CreateOrUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a segment by its supplied ID
func (c *Client) Get(
	ctx context.Context,
	// The reference ID of the segment to get. All other entity ID fields are inferred from the request.
	segmentReferenceID string,
	request *mavenagigo.SegmentGetRequest,
	opts ...option.RequestOption,
) (*mavenagigo.SegmentResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		segmentReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update mutable segment fields
//
// The `appId` field can be provided to update a segment owned by a different app.
// All other fields will overwrite the existing value on the segment only if provided.
func (c *Client) Patch(
	ctx context.Context,
	// The reference ID of the segment to update. All other entity ID fields are inferred from the request.
	segmentReferenceID string,
	request *mavenagigo.SegmentPatchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.SegmentResponse, error) {
	response, err := c.WithRawResponse.Patch(
		ctx,
		segmentReferenceID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
