// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppID == "" {
		options.AppID = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Search across all agent users on an agent.
//
// Agent users are a merged view of the users created by individual apps.
func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.AgentUserSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.AgentUserSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get an agent user by its supplied ID.
//
// Agent users are a merged view of the users created by individual apps.
func (c *Client) GetAgentUser(
	ctx context.Context,
	// The ID of the agent user to get.
	agentUserID string,
	opts ...option.RequestOption,
) (*mavenagigo.AgentUser, error) {
	response, err := c.WithRawResponse.GetAgentUser(
		ctx,
		agentUserID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an app user or create it if it doesn't exist.
func (c *Client) CreateOrUpdate(
	ctx context.Context,
	request *mavenagigo.AppUserRequest,
	opts ...option.RequestOption,
) (*mavenagigo.AppUserResponse, error) {
	response, err := c.WithRawResponse.CreateOrUpdate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get an app user by its supplied ID
func (c *Client) Get(
	ctx context.Context,
	// The reference ID of the app user to get. All other entity ID fields are inferred from the request.
	userID string,
	request *mavenagigo.UserGetRequest,
	opts ...option.RequestOption,
) (*mavenagigo.AppUserResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes all identifiers and user data saved by the specified app.
// Does not modify data or identifiers saved by other apps.
//
// If this user is linked to a user from another app, it will not be unlinked. Unlinking of users is not yet supported.
//
// <Warning>This is a destructive operation and cannot be undone.</Warning>
func (c *Client) Delete(
	ctx context.Context,
	// The reference ID of the app user to delete. All other entity ID fields are inferred from the request.
	userID string,
	request *mavenagigo.UserDeleteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		userID,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
