// Code generated by Fern. DO NOT EDIT.

package segments_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	client "github.com/mavenagi/mavenagi-go/client"
	option "github.com/mavenagi/mavenagi-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSegmentsSearchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.SegmentsSearchRequest{}
	_, invocationErr := client.Segments.Search(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/segments", nil, 1)
}

func TestSegmentsCreateOrUpdateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.SegmentRequest{
		SegmentID: &mavenagigo.EntityIDBase{
			ReferenceID: "admin-users",
		},
		Name: "Admin users",
		Precondition: &mavenagigo.Precondition{
			Group: &mavenagigo.PreconditionGroup{
				Operator: mavenagigo.PreconditionGroupOperatorAnd,
				Preconditions: []*mavenagigo.Precondition{
					&mavenagigo.Precondition{
						User: &mavenagigo.MetadataPrecondition{
							Key: "userKey",
						},
					},
					&mavenagigo.Precondition{
						User: &mavenagigo.MetadataPrecondition{
							Key: "userKey2",
						},
					},
				},
			},
		},
	}
	_, invocationErr := client.Segments.CreateOrUpdate(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PUT", "/v1/segments", nil, 1)
}

func TestSegmentsGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.SegmentGetRequest{}
	_, invocationErr := client.Segments.Get(
		context.TODO(),
		"admin-users",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v1/segments/admin-users", nil, 1)
}

func TestSegmentsPatchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.SegmentPatchRequest{}
	_, invocationErr := client.Segments.Patch(
		context.TODO(),
		"segmentReferenceId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v1/segments/segmentReferenceId", nil, 1)
}
