// Code generated by Fern. DO NOT EDIT.

package agents

import (
	context "context"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	core "github.com/mavenagi/mavenagi-go/core"
	internal "github.com/mavenagi/mavenagi-go/internal"
	option "github.com/mavenagi/mavenagi-go/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AppId == "" {
		options.AppId = os.Getenv("MAVENAGI_APP_ID")
	}
	if options.AppSecret == "" {
		options.AppSecret = os.Getenv("MAVENAGI_APP_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Search for agents across all organizations.
//
// <Tip>
// This endpoint requires additional permissions. Contact support to request access.
// </Tip>
func (c *Client) Search(
	ctx context.Context,
	request *mavenagigo.AgentsSearchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.AgentsSearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists all agents for an organization
func (c *Client) List(
	ctx context.Context,
	// The ID of the organization.
	organizationReferenceId string,
	opts ...option.RequestOption,
) ([]*mavenagigo.Agent, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		organizationReferenceId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new agent
//
// <Tip>
// This endpoint requires additional permissions. Contact support to request access.
// </Tip>
func (c *Client) Create(
	ctx context.Context,
	// The ID of the organization.
	organizationReferenceId string,
	// The ID of the agent.
	agentReferenceId string,
	request *mavenagigo.CreateAgentRequest,
	opts ...option.RequestOption,
) (*mavenagigo.Agent, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		organizationReferenceId,
		agentReferenceId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get an agent
func (c *Client) Get(
	ctx context.Context,
	// The ID of the organization.
	organizationReferenceId string,
	// The ID of the agent.
	agentReferenceId string,
	opts ...option.RequestOption,
) (*mavenagigo.Agent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		organizationReferenceId,
		agentReferenceId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update mutable agent fields
// All fields will overwrite the existing value on the agent only if provided.
//
// <Tip>
// This endpoint requires additional permissions. Contact support to request access.
// </Tip>
func (c *Client) Patch(
	ctx context.Context,
	// The ID of the organization.
	organizationReferenceId string,
	// The ID of the agent.
	agentReferenceId string,
	request *mavenagigo.AgentPatchRequest,
	opts ...option.RequestOption,
) (*mavenagigo.Agent, error) {
	response, err := c.WithRawResponse.Patch(
		ctx,
		organizationReferenceId,
		agentReferenceId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an agent.
//
// <Tip>
// This endpoint requires additional permissions. Contact support to request access.
// </Tip>
func (c *Client) Delete(
	ctx context.Context,
	// The ID of the organization.
	organizationReferenceId string,
	// The ID of the agent.
	agentReferenceId string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		organizationReferenceId,
		agentReferenceId,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
