// Code generated by Fern. DO NOT EDIT.

package conversation_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	mavenagigo "github.com/mavenagi/mavenagi-go"
	client "github.com/mavenagi/mavenagi-go/client"
	option "github.com/mavenagi/mavenagi-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestConversationInitializeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationRequest{
		ConversationID: &mavenagigo.EntityIDBase{
			ReferenceID: "x",
		},
		Messages: []*mavenagigo.ConversationMessageRequest{
			&mavenagigo.ConversationMessageRequest{
				ConversationMessageID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				UserID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				Text:            "text",
				UserMessageType: mavenagigo.UserConversationMessageTypeUser,
			},
			&mavenagigo.ConversationMessageRequest{
				ConversationMessageID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				UserID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				Text:            "text",
				UserMessageType: mavenagigo.UserConversationMessageTypeUser,
			},
		},
	}
	_, invocationErr := client.Conversation.Initialize(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations", nil, 1)
}

func TestConversationPatchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationPatchRequest{
		LlmEnabled: mavenagigo.Bool(
			true,
		),
	}
	_, invocationErr := client.Conversation.Patch(
		context.TODO(),
		"conversation-0",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v1/conversations/conversation-0", nil, 1)
}

func TestConversationGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationGetRequest{}
	_, invocationErr := client.Conversation.Get(
		context.TODO(),
		"conversationId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v1/conversations/conversationId", nil, 1)
}

func TestConversationDeleteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationDeleteRequest{
		Reason: "GDPR deletion request 1234.",
	}
	invocationErr := client.Conversation.Delete(
		context.TODO(),
		"conversation-0",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/v1/conversations/conversation-0", map[string]string{"reason": "GDPR deletion request 1234."}, 1)
}

func TestConversationAppendNewMessagesWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := []*mavenagigo.ConversationMessageRequest{
		&mavenagigo.ConversationMessageRequest{
			ConversationMessageID: &mavenagigo.EntityIDBase{
				ReferenceID: "x",
			},
			UserID: &mavenagigo.EntityIDBase{
				ReferenceID: "x",
			},
			Text:            "text",
			UserMessageType: mavenagigo.UserConversationMessageTypeUser,
		},
		&mavenagigo.ConversationMessageRequest{
			ConversationMessageID: &mavenagigo.EntityIDBase{
				ReferenceID: "x",
			},
			UserID: &mavenagigo.EntityIDBase{
				ReferenceID: "x",
			},
			Text:            "text",
			UserMessageType: mavenagigo.UserConversationMessageTypeUser,
		},
	}
	_, invocationErr := client.Conversation.AppendNewMessages(
		context.TODO(),
		"conversationId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversationId/messages", nil, 1)
}

func TestConversationAskWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.AskRequest{
		ConversationMessageID: &mavenagigo.EntityIDBase{
			ReferenceID: "message-0",
		},
		UserID: &mavenagigo.EntityIDBase{
			ReferenceID: "user-0",
		},
		Text: "How do I reset my password?",
		Attachments: []*mavenagigo.AttachmentRequest{
			&mavenagigo.AttachmentRequest{
				Type:    "image/png",
				Content: []byte("iVBORw0KGgo..."),
			},
		},
		TransientData: map[string]string{
			"userToken":   "abcdef123",
			"queryApiKey": "foobar456",
		},
		Timezone: mavenagigo.String(
			"America/New_York",
		),
	}
	_, invocationErr := client.Conversation.Ask(
		context.TODO(),
		"conversation-0",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversation-0/ask", nil, 1)
}

func TestConversationAskStreamWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.AskRequest{
		ConversationMessageID: &mavenagigo.EntityIDBase{
			ReferenceID: "message-0",
		},
		UserID: &mavenagigo.EntityIDBase{
			ReferenceID: "user-0",
		},
		Text: "How do I reset my password?",
		Attachments: []*mavenagigo.AttachmentRequest{
			&mavenagigo.AttachmentRequest{
				Type:    "image/png",
				Content: []byte("iVBORw0KGgo..."),
			},
		},
		TransientData: map[string]string{
			"userToken":   "abcdef123",
			"queryApiKey": "foobar456",
		},
		Timezone: mavenagigo.String(
			"America/New_York",
		),
	}
	_, invocationErr := client.Conversation.AskStream(
		context.TODO(),
		"conversation-0",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversation-0/ask_stream", nil, 1)
}

func TestConversationCategorizeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Conversation.Categorize(
		context.TODO(),
		"conversationId",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversationId/categorize", nil, 1)
}

func TestConversationCreateFeedbackWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.FeedbackRequest{
		FeedbackID: &mavenagigo.EntityIDBase{
			ReferenceID: "feedback-0",
		},
		UserID: &mavenagigo.EntityIDBase{
			ReferenceID: "user-0",
		},
		ConversationID: &mavenagigo.EntityIDBase{
			ReferenceID: "conversation-0",
		},
		ConversationMessageID: &mavenagigo.EntityIDBase{
			ReferenceID: "message-1",
		},
		Type: mavenagigo.FeedbackTypeThumbsUp,
		Text: mavenagigo.String(
			"Great answer!",
		),
	}
	_, invocationErr := client.Conversation.CreateFeedback(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/feedback", nil, 1)
}

func TestConversationSubmitActionFormWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.SubmitActionFormRequest{
		ActionFormID: "actionFormId",
		Parameters: map[string]*mavenagigo.ActionFormRequestParamValue{
			"parameters": &mavenagigo.ActionFormRequestParamValue{
				Unknown: map[string]any{
					"key": "value",
				},
			},
		},
	}
	_, invocationErr := client.Conversation.SubmitActionForm(
		context.TODO(),
		"conversationId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversationId/submit-form", nil, 1)
}

func TestConversationAddConversationMetadataWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := map[string]string{
		"string": "string",
	}
	_, invocationErr := client.Conversation.AddConversationMetadata(
		context.TODO(),
		"conversationId",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/conversationId/metadata", nil, 1)
}

func TestConversationUpdateConversationMetadataWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.UpdateMetadataRequest{
		AppID: mavenagigo.String(
			"conversation-owning-app",
		),
		Values: map[string]string{
			"key": "newValue",
		},
	}
	_, invocationErr := client.Conversation.UpdateConversationMetadata(
		context.TODO(),
		"conversation-0",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PUT", "/v1/conversations/conversation-0/metadata", nil, 1)
}

func TestConversationSearchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationsSearchRequest{}
	_, invocationErr := client.Conversation.Search(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/search", nil, 1)
}

func TestConversationExportWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.ConversationsSearchRequest{}
	_, invocationErr := client.Conversation.Export(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/export", nil, 1)
}

func TestConversationDeliverMessageWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewMavenAGI(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &mavenagigo.DeliverMessageRequest{
		User: &mavenagigo.DeliverUserMessageRequest{
			UserID: &mavenagigo.EntityIDWithoutAgent{
				Type:        mavenagigo.EntityTypeAgent,
				AppID:       "appId",
				ReferenceID: "x",
			},
			Message: &mavenagigo.ConversationMessageRequest{
				ConversationMessageID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				UserID: &mavenagigo.EntityIDBase{
					ReferenceID: "x",
				},
				Text:            "text",
				UserMessageType: mavenagigo.UserConversationMessageTypeUser,
			},
		},
	}
	_, invocationErr := client.Conversation.DeliverMessage(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/conversations/deliver-message", nil, 1)
}
